import {
  SETUP_ACTION_PATH,
  SETUP_WORKFLOW_PATH,
  setupActionYaml,
  setupWorkflowYaml,
} from "./setup-workflow.ts";

export const REMEDIATION_BRANCH = "nospoilers/remediate";

export const REMEDIATION_PERMISSIONS = [
  "Contents: Read and write (create the remediation branch; not Administration)",
  "Pull requests: Read and write (open a reviewable PR; never merge it)",
] as const;

export type RemediationFile = {
  path: string;
  content: string;
};

const CUSTOMER_OWNED_PATHS = new Set([
  ".gitignore",
  ".npmignore",
  ".nospoilers.yml",
  SETUP_WORKFLOW_PATH,
  SETUP_ACTION_PATH,
]);

export function remediationGitignore(): string {
  return `# Generated by NoSpoilers. Review this PR; it is never merged automatically.
# Keep source maps and env files out of git so they cannot land in a packed artifact.
*.map
.env
.env.*
!.env.example
`;
}

export function remediationNpmignore(): string {
  return `# Generated by NoSpoilers. Review this PR; it is never merged automatically.
# If package.json has a "files" field, npm ignores this file — use the package-files snippet.
*.map
.env
.env.*
`;
}

export function remediationPolicyYaml(): string {
  return `# Generated by NoSpoilers. Review this PR; it is never merged automatically.
# Empty policy on purpose. Do not add allow entries here to silence a critical finding.
# Use Watch for expiring, attributable exceptions instead of shipping with secrets or maps.
version: 1
strict: false
`;
}

export function remediationBundlerHints(): string {
  return `# Bundler hints from NoSpoilers

This file is documentation. It does not rewrite your bundler config.
The App never merges this pull request.

Production builds should not emit source maps into the packed artifact.

## Vite

\`\`\`js
export default { build: { sourcemap: false } }
\`\`\`

## webpack

Set \`devtool: false\` for production.

## esbuild / Rollup

Set \`sourcemap: false\` (esbuild) or \`output.sourcemap = false\` (Rollup).

Do not commit \`*.map\` files. Keep \`.env\` out of the pack.
`;
}

export function remediationPackageFilesSnippet(): string {
  return `${JSON.stringify(
    {
      files: ["dist", "README.md", "LICENSE"],
      comment:
        "Copy the files array into package.json if you publish with the files field. .npmignore is ignored when files is set. Do not include *.map or .env.",
    },
    null,
    2,
  )}\n`;
}

export function remediationBundle(): RemediationFile[] {
  return [
    { path: ".gitignore", content: remediationGitignore() },
    { path: ".npmignore", content: remediationNpmignore() },
    { path: ".nospoilers.yml", content: remediationPolicyYaml() },
    { path: ".nospoilers/bundler-hints.md", content: remediationBundlerHints() },
    { path: ".nospoilers/package-files.snippet.json", content: remediationPackageFilesSnippet() },
    { path: SETUP_WORKFLOW_PATH, content: setupWorkflowYaml() },
    { path: SETUP_ACTION_PATH, content: setupActionYaml() },
  ];
}

export function isCustomerOwnedRemediationPath(filePath: string): boolean {
  return CUSTOMER_OWNED_PATHS.has(filePath);
}

export function remediationWrites(existingPaths: string[]): RemediationFile[] {
  const existing = new Set(existingPaths.map((row) => row.replace(/^\.\//, "")));
  const writes: RemediationFile[] = [];
  for (const file of remediationBundle()) {
    if (existing.has(file.path) && isCustomerOwnedRemediationPath(file.path)) {
      if (file.path === ".gitignore") {
        writes.push({ path: ".nospoilers/gitignore.append", content: file.content });
      }
      if (file.path === ".npmignore") {
        writes.push({ path: ".nospoilers/npmignore.append", content: file.content });
      }
      continue;
    }
    writes.push(file);
  }
  return writes;
}

export function remediationPullRequestTitle(): string {
  return "Keep maps and env files out of the packed artifact";
}

export function remediationPullRequestBody(): string {
  return [
    "This pull request is from NoSpoilers. It is **not** merged automatically.",
    "",
    "It adds **ignore rules**, an **empty** `.nospoilers.yml` (no silent allowlist), bundler",
    "hints, a `package.json` `files` snippet, and the packed-artifact CI workflow plus vendored",
    "hosted-scan Action if they are missing.",
    "Existing customer `.gitignore`, `.npmignore`, `.nospoilers.yml`, workflow, and Action files are not overwritten.",
    "",
    "This is not a destructive action. It does **not** make the repository private, delete a",
    "Release asset, or disable a workflow. Those stay opt-in and confirmed later.",
    "",
    "Required GitHub App permissions (shown before you opened this):",
    "",
    "- Contents: Read and write (not Administration)",
    "- Pull requests: Read and write (never merge)",
    "",
    "Do **not** grant Administration on all repositories.",
    "",
    "After you merge:",
    "",
    "1. Confirm production bundlers do not emit `*.map` into the artifact you publish.",
    "2. If `package.json` uses `files`, copy `.nospoilers/package-files.snippet.json` — `.npmignore` is ignored.",
    "3. Keep Contents write and Pull requests write if you want later setup or remediation PRs.",
  ].join("\n");
}

export function remediationCommitMessage(): string {
  return "Add NoSpoilers ignore rules, empty policy, bundler hints, and packed-artifact CI.";
}
