export const SETUP_WORKFLOW_PATH = ".github/workflows/nospoilers.yml";
export const SETUP_BRANCH = "nospoilers/setup";

export const SETUP_PERMISSIONS = [
  "Contents: Read and write (create the workflow branch; not Administration)",
  "Pull requests: Read and write (open a reviewable PR; never merge it)",
  "Checks: Read and write (optional; report release-scan results on the tag SHA)",
] as const;

export function setupWorkflowYaml(): string {
  return `# Generated by NoSpoilers. Review this PR; it is never merged automatically.
# Scans a packed artifact only. Push events that change source are not unpacked.
name: NoSpoilers

on:
  workflow_dispatch:
    inputs:
      path:
        description: Packed artifact (.tgz, .zip, or .asar) relative to the repo root
        required: true
        default: package.tgz
  push:
    paths:
      - package.tgz
      - dist/*.tgz
      - dist/*.zip
      - dist/*.asar
  pull_request:
    paths:
      - package.tgz
      - dist/*.tgz
      - dist/*.zip
      - dist/*.asar

jobs:
  nospoilers:
    name: NoSpoilers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmotiveImpact/nospoilers@main
        with:
          path: \${{ github.event.inputs.path || 'package.tgz' }}
`;
}

export function setupPullRequestTitle(): string {
  return "Add NoSpoilers pack scan to CI";
}

export function setupPullRequestBody(): string {
  return [
    "This pull request is from NoSpoilers. It is **not** merged automatically.",
    "",
    "It adds a GitHub Action that scans a **packed** artifact (npm tarball, zip, or Electron asar).",
    "It does not unpack the git tree on ordinary source pushes.",
    "",
    "After you merge:",
    "",
    "1. Confirm the `path` input matches the file you publish (`package.tgz`, `dist/app.asar`, …).",
    "2. Optionally mark the **NoSpoilers** check as required in branch protection.",
    "3. Keep Contents write and Pull requests write if you want NoSpoilers to open later setup PRs.",
    "4. Do **not** grant Administration on all repositories.",
    "",
    "The hosted GitHub App still scans **Release assets** on our servers. This workflow is the",
    "pre-publish CI gate on yours.",
    "",
    "Optional: mint a scan API token on Watch and set `api-url` / `api-token` on the Action to",
    "POST the pack to `/api/v1/scan` instead of scanning locally.",
  ].join("\n");
}

export function setupCommitMessage(): string {
  return "Add NoSpoilers packed-artifact scan workflow.";
}
