import { PACK_FILE_RE } from "../scanner/formats.ts";

export const SETUP_WORKFLOW_PATH = ".github/workflows/nospoilers.yml";
export const SETUP_BRANCH = "nospoilers/setup";
export const MAX_SETUP_PACKS = 8;

export const SETUP_PACK_GLOBS = [
  "package.tgz",
  "dist/*.tgz",
  "dist/*.tar.gz",
  "dist/*.tar",
  "dist/*.zip",
  "dist/*.asar",
  "dist/*.vsix",
  "dist/*.whl",
  "dist/*.jar",
  "dist/*.war",
  "dist/*.nupkg",
  "dist/*.snupkg",
  "dist/*.crx",
  "dist/*.xpi",
  "dist/*.gem",
  "dist/*.apk",
  "dist/*.aab",
  "dist/*.ipa",
  "dist/*.xapk",
] as const;

export const SETUP_PERMISSIONS = [
  "Contents: Read and write (create the workflow branch; not Administration)",
  "Pull requests: Read and write (open a reviewable PR; never merge it)",
  "Checks: Read and write (optional; report release-scan results on the tag SHA)",
] as const;

function yamlPathFilters(indent: string): string {
  return SETUP_PACK_GLOBS.map((glob) => `${indent}- ${glob}`).join("\n");
}

export function setupWorkflowYaml(): string {
  const filters = yamlPathFilters("      ");
  const globEnv = JSON.stringify([...SETUP_PACK_GLOBS]);
  return `# Generated by NoSpoilers. Review this PR; it is never merged automatically.
# Scans packed artifacts that exist (package.tgz and dist/* packs). Source pushes are not unpacked.
name: NoSpoilers

on:
  workflow_dispatch:
    inputs:
      path:
        description: Packed artifact (.tgz, .tar, .zip, .vsix, .whl, .jar, …) relative to the repo root
        required: true
        default: package.tgz
  push:
    paths:
${filters}
  pull_request:
    paths:
${filters}

jobs:
  list-packs:
    name: List packed artifacts
    runs-on: ubuntu-latest
    outputs:
      packs: \${{ steps.list.outputs.packs }}
    steps:
      - uses: actions/checkout@v4
      - id: list
        name: Resolve pack paths
        env:
          NS_DISPATCH_PATH: \${{ github.event.inputs.path }}
          NS_MAX_PACKS: "${MAX_SETUP_PACKS}"
          NS_PACK_GLOBS: '${globEnv}'
          NS_PACK_RE: '${PACK_FILE_RE.source}'
        run: |
          python3 - <<'PY'
          import glob, json, os, re
          from pathlib import Path

          pack_re = re.compile(os.environ["NS_PACK_RE"], re.I)

          def usable(raw: str) -> bool:
              path = Path(raw)
              if path.is_absolute() or ".." in path.parts:
                  return False
              if path.is_symlink() or not path.is_file():
                  return False
              name = str(path).replace("\\\\", "/")
              return bool(pack_re.search(name))

          max_packs = int(os.environ.get("NS_MAX_PACKS", "8"))
          globs = json.loads(os.environ["NS_PACK_GLOBS"])
          event = os.environ.get("GITHUB_EVENT_NAME", "")
          dispatch = (os.environ.get("NS_DISPATCH_PATH") or "").strip()
          packs = []
          if event == "workflow_dispatch" and dispatch:
              if not usable(dispatch):
                  raise SystemExit("workflow_dispatch path must be a relative packed file that exists.")
              packs = [dispatch.replace("\\\\", "/")]
          else:
              seen = set()
              for pattern in globs:
                  for match in glob.glob(pattern):
                      name = match.replace("\\\\", "/")
                      if name in seen or not usable(name):
                          continue
                      seen.add(name)
                      packs.append(name)
              packs = sorted(packs)[:max_packs]
          output = Path(os.environ["GITHUB_OUTPUT"])
          with output.open("a", encoding="utf-8") as fh:
              fh.write("packs<<NS_PACKS\\n")
              fh.write(json.dumps(packs) + "\\n")
              fh.write("NS_PACKS\\n")
          PY

  nospoilers:
    name: NoSpoilers
    needs: list-packs
    if: needs.list-packs.outputs.packs != '[]'
    strategy:
      fail-fast: true
      matrix:
        pack: \${{ fromJSON(needs.list-packs.outputs.packs) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmotiveImpact/nospoilers@main
        with:
          path: \${{ matrix.pack }}

  nospoilers-missing:
    name: No packed artifact
    needs: list-packs
    if: needs.list-packs.outputs.packs == '[]'
    runs-on: ubuntu-latest
    steps:
      - name: Fail closed
        run: |
          echo "No packed artifact found. Add package.tgz or a pack under dist/, or dispatch with a path." >&2
          exit 1
`;
}

export function setupPullRequestTitle(): string {
  return "Add NoSpoilers pack scan to CI";
}

export function setupPullRequestBody(): string {
  return [
    "This pull request is from NoSpoilers. It is **not** merged automatically.",
    "",
    "It adds a GitHub Action that scans **packed** artifacts that exist: `package.tgz` and matching files under `dist/` (npm tarball, zip, VSIX, wheel, JAR, gem, Docker/OCI image, APK/IPA, Lambda zip, or Electron asar).",
    "Each existing pack is scanned. If none exist, the workflow fails closed. It does not unpack the git tree on ordinary source pushes.",
    "",
    "After you merge:",
    "",
    "1. Put the file you publish at `package.tgz` or under `dist/`, or dispatch the workflow with a path.",
    "2. Optionally mark the **NoSpoilers** check as required in branch protection.",
    "3. Keep Contents write and Pull requests write if you want NoSpoilers to open later setup PRs.",
    "4. Do **not** grant Administration on all repositories.",
    "",
    "The hosted GitHub App still scans **Release assets** on our servers. This workflow is the",
    "pre-publish CI gate on yours.",
    "",
    "Optional: mint a scan API token on Watch and set `api-url` / `api-token` on the Action to",
    "POST the pack to `/api/v1/scan` instead of scanning locally.",
  ].join("\n");
}

export function setupCommitMessage(): string {
  return "Add NoSpoilers packed-artifact scan workflow.";
}
