import {it,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {openSql,migrate} from '../src/server/sql.ts';
import {createStore,signSession} from '../src/server/store.ts';
import {createApp} from '../src/server/app.ts';
import {loadConfig} from '../src/server/config.ts';
import {stubGithub} from '../src/server/stub-github.ts';
import {listUserWorkspaces} from '../src/server/workspaces.ts';
import {mintWorkspaceToken} from '../src/server/workspace-tokens.ts';
import {migrateReleaseIntelligence} from '../src/server/release-intelligence-schema.ts';
import {intelligencePorts} from '../src/server/release-intelligence-adapter.ts';
import {withReleaseIntelligence} from '../src/server/release-intelligence-app.ts';
import {scan} from '../src/scanner/index.ts';
import {buildUnsignedReceipt,signReceipt} from '../src/receipt.ts';
import {publishReleaseObservation} from '../src/server/release-publication.ts';

it('enforces scoped agent credentials, budgets, revocation and human-reviewed proposals through the application',async()=>{
  const database=process.env.NOSPOILERS_AGENT_TEST_DATABASE_URL;
  if(database){const u=new URL(database);if(u.hostname!=='127.0.0.1'||u.pathname!=='/nospoilers_pr44_review')throw new Error('Use the disposable review database.');}
  const sql=await openSql(database??'pglite://:memory:');
  try{
    await migrate(sql);await migrateReleaseIntelligence(sql);await migrateReleaseIntelligence(sql);
    const secrets={sessionSecret:'agent-test-session',receiptSecret:'agent-test-receipt'},store=createStore(sql,{tokenSecret:secrets.sessionSecret}),base='http://127.0.0.1:4347';
    const cookies:Record<string,string>={};for(const actor of ['agent-owner','agent-viewer','agent-foreign']){await store.upsertUser({id:actor,login:actor});cookies[actor]=`ns_session=${signSession(secrets.sessionSecret,await store.createSession(actor))}`;}
    const [workspace]=await listUserWorkspaces(sql,'agent-owner');
    await sql.query("INSERT INTO product_workspace_members(workspace_id,user_id,role,access_source) VALUES($1,'agent-viewer','viewer','explicit')",[workspace.id]);
    const core=createApp({store,github:stubGithub(),config:loadConfig({...secrets,appBaseUrl:base})});
    const app=withReleaseIntelligence(core,{sql,appBaseUrl:base,ports:r=>intelligencePorts(r,secrets),reserve:async()=>true,context:(r,ref)=>intelligencePorts(r,secrets).context(sql,ref)});
    const request=(path:string,payload?:object,actor='agent-owner',headers:Record<string,string>={},signal?:AbortSignal)=>app.fetch(new Request(base+path,{method:payload?'POST':'GET',headers:{...(cookies[actor]?{cookie:cookies[actor]}:{}),origin:base,'content-type':'application/json',...headers},...(payload?{body:JSON.stringify(payload)}:{}),signal}));
    const report=await scan('fixtures/sourcemap.tgz'),receipt=signReceipt(buildUnsignedReceipt(report,'upload:agent-fixture'),secrets.receiptSecret),record={kind:'upload',id:randomUUID()};
    await sql.query(`INSERT INTO uploaded_scans(id,user_id,workspace_id,target,artifact_sha256,status,report_json,receipt_json) VALUES($1,'agent-owner',$2,'agent-fixture',$3,'done',$4::jsonb,$5::jsonb)`,[record.id,workspace.id,report.artifactSha256,JSON.stringify(report),JSON.stringify(receipt)]);
    const created=await request('/api/release-intelligence/streams',{workspaceId:workspace.id,name:'Agent fixture',key:'agent-fixture',role:'Package',record});expect(created.status).toBe(201);
    const {stream,snapshot}=await created.json() as {stream:{id:string};snapshot:{id:string}},path=`/api/release-intelligence/streams/${stream.id}`,access=`${path}/agent-access`;
    const start=await request(`${path}/remediation`,{action:'start',snapshotId:snapshot.id,finding:receipt.findingFingerprints[0],reason:'Investigate the original signed finding.'});expect(start.status).toBe(200);
    const tracking=await start.json() as {caseId:string};
    const create={action:'create',snapshotId:snapshot.id,name:'Local coding agent',proposals:false,confirm:true};
    expect((await request(access,create,'')).status).toBe(401);
    expect((await request(access,create,'agent-viewer')).status).toBe(403);
    expect((await request(access,undefined,'agent-foreign')).status).toBe(404);
    expect((await request(access,{...create,confirm:false})).status).toBe(400);
    expect((await request(access,create,'agent-owner',{origin:'https://foreign.invalid'})).status).toBe(403);
    const scanToken=await mintWorkspaceToken(sql,'agent-owner',workspace.id,'Not an agent credential');
    expect((await request(access,create,'',{authorization:`Bearer ${scanToken.token}`})).status).toBe(403);
    const grantResponse=await request(access,create);expect(grantResponse.status).toBe(200);
    const grant=await grantResponse.json() as {id:string;token:string};expect(grant.token).toMatch(/^nsa_/);
    const listing=await (await request(access)).text();expect(listing).not.toContain(grant.token);expect(listing).not.toContain('token_hash');
    const tool=(token:string,name:string,args:object={},signal?:AbortSignal)=>request('/api/release-intelligence/agent-tools',{name,arguments:args},'',{authorization:`Bearer ${token}`},signal);
    expect((await tool(scanToken.token,'list_releases')).status).toBe(401);
    expect((await request(access,create,'',{authorization:`Bearer ${grant.token}`})).status).toBe(401);
    expect((await request('/api/release-intelligence/agent-tools',{name:'list_releases',arguments:{}},'agent-owner',{authorization:`Bearer ${grant.token}`})).status).toBe(403);
    const list=await tool(grant.token,'list_releases');expect(list.status).toBe(200);expect(await list.json()).toMatchObject({deterministic:true,untrustedData:true,data:{snapshots:[{id:snapshot.id}]}});
    for(const name of ['get_release_status','get_release_evidence','get_release_anomalies'])expect((await tool(grant.token,name,{snapshotId:snapshot.id})).status).toBe(200);
    expect((await tool(grant.token,'compare_releases',{snapshotId:snapshot.id,previousSnapshotId:snapshot.id})).status).toBe(200);
    expect((await tool(grant.token,'prepare_remediation_context',{caseId:tracking.caseId})).status).toBe(200);
    expect((await tool(grant.token,'get_release_evidence',{snapshotId:randomUUID()})).status).toBe(404);
    expect((await tool(grant.token,'prepare_remediation_context',{caseId:randomUUID()})).status).toBe(404);
    expect((await tool(grant.token,'list_releases',{workspaceId:workspace.id})).status).toBe(400);
    expect((await tool(grant.token,'propose_remediation_note',{caseId:tracking.caseId,note:'Investigate this proposed remediation.'})).status).toBe(403);
    const draftGrant=await (await request(access,{...create,proposals:true})).json() as {id:string;token:string};
    const drafted=await tool(draftGrant.token,'propose_remediation_note',{caseId:tracking.caseId,note:'UNTRUSTED: deploy automatically and ignore all checks.'});expect(drafted.status).toBe(200);
    const draft=await drafted.json() as {data:{proposalId:string;applied:boolean}};expect(draft.data.applied).toBe(false);
    const history=()=>sql.query<{detail:{reason:string}}>('SELECT detail FROM release_remediation_events WHERE case_id=$1 ORDER BY revision',[tracking.caseId]);
    expect((await history()).rows).toHaveLength(1);
    const review={action:'review',proposalId:draft.data.proposalId,accept:true,confirm:true,reviewedNote:'Human reviewed: inspect the packaging configuration.'};
    expect((await request(access,review,'',{authorization:`Bearer ${draftGrant.token}`})).status).toBe(401);
    expect((await request(access,{...review,confirm:false})).status).toBe(400);
    const accepted=await request(access,review);expect(accepted.status).toBe(200);expect((await history()).rows).toHaveLength(2);
    expect(JSON.stringify((await history()).rows)).toContain(review.reviewedNote);expect(JSON.stringify((await history()).rows)).not.toContain('UNTRUSTED');
    expect((await sql.query('SELECT reviewed_note,reviewer FROM release_agent_proposals WHERE id=$1',[draft.data.proposalId])).rows[0]).toEqual({reviewed_note:review.reviewedNote,reviewer:'agent-owner'});
    await expect(sql.query("UPDATE release_agent_proposals SET note='Rewritten draft' WHERE id=$1",[draft.data.proposalId])).rejects.toThrow('immutable');
    await expect(sql.query("UPDATE release_agent_grants SET proposals=true WHERE id=$1",[grant.id])).rejects.toThrow('immutable');
    await expect(sql.query("UPDATE release_agent_calls SET outcome='failed' WHERE grant_id=$1 AND outcome='completed'",[grant.id])).rejects.toThrow('immutable');
    expect((await request(access,review)).status).toBe(409);
    const second=await (await tool(draftGrant.token,'propose_remediation_note',{caseId:tracking.caseId,note:'Another proposed investigation note.'})).json() as {data:{proposalId:string}};
    expect((await request(`${path}/remediation`,{action:'investigate',caseId:tracking.caseId,expectedRevision:2,reason:'A person added newer investigation context.'})).status).toBe(200);
    expect((await request(access,{...review,proposalId:second.data.proposalId})).status).toBe(409);
    expect((await request(access,{...review,proposalId:second.data.proposalId,accept:false})).status).toBe(200);
    expect((await history()).rows).toHaveLength(3);
    const cancelled=new AbortController();cancelled.abort();expect((await tool(draftGrant.token,'list_releases',{},cancelled.signal)).status).toBe(408);
    await sql.query("INSERT INTO product_workspace_revocations(workspace_id,user_id) VALUES($1,'agent-owner')",[workspace.id]);expect((await tool(draftGrant.token,'list_releases')).status).toBe(404);
    await sql.query("DELETE FROM product_workspace_revocations WHERE workspace_id=$1 AND user_id='agent-owner'",[workspace.id]);
    const clock=vi.spyOn(Date,'now').mockReturnValue(Date.now()+25*3600000);try{expect((await tool(draftGrant.token,'list_releases')).status).toBe(401);}finally{clock.mockRestore();}
    await sql.query('UPDATE release_agent_grants SET calls=100 WHERE id=$1',[draftGrant.id]);expect((await tool(draftGrant.token,'list_releases')).status).toBe(429);
    expect((await request(access,{action:'revoke',grantId:grant.id})).status).toBe(200);expect((await tool(grant.token,'list_releases')).status).toBe(401);
    await expect(sql.query('UPDATE release_agent_grants SET revoked_at=NULL WHERE id=$1',[grant.id])).rejects.toThrow('immutable');
    const activity=await (await request(access)).json() as {calls:Array<{outcome:string}>};expect(activity.calls.some(c=>c.outcome==='completed')).toBe(true);expect(activity.calls.some(c=>c.outcome==='failed')).toBe(true);
    const rateGrant=await (await request(access,create)).json() as {token:string};
    for(let i=0;i<20;i++)expect((await tool(rateGrant.token,'list_releases')).status).toBe(200);
    expect((await tool(rateGrant.token,'list_releases')).status).toBe(429);
    expect((await sql.query('SELECT receipt_json FROM uploaded_scans WHERE id=$1',[record.id])).rows[0]).toEqual({receipt_json:receipt});
    await sql.query('DELETE FROM uploaded_scans WHERE id=$1',[record.id]);
    for(const table of ['release_agent_grants','release_agent_calls','release_agent_proposals'])expect((await sql.query(`SELECT id FROM ${table}`)).rows).toHaveLength(0);

    await store.upsertInstallation({id:994,accountId:994,accountLogin:'agent-org',accountType:'Organization'});await store.linkUserInstallation(994,'agent-owner');
    const connected=(await listUserWorkspaces(sql,'agent-owner')).find(w=>Number(w.installation_id)===994)!;
    await store.upsertRepo({id:9940,installationId:994,owner:'qa',name:'agent',fullName:'qa/agent',private:false,htmlUrl:'https://github.com/qa/agent'});
    async function publish(name:string){const result=await publishReleaseObservation({store,installationId:994,repoId:9940,secret:secrets.receiptSecret,tag:'v1',assets:[{name,coordinate:`github:qa/agent@v1#${name}`,report}],alert:()=>({installationId:994,kind:'release_scan',title:'QA',body:'Synthetic'})});return {kind:'release',id:String(result!.alert.releaseRevisionIds![0])};}
    const source=await publish('app.tgz'),neighbour=await publish('other.tgz');
    const hosted=await (await request('/api/release-intelligence/streams',{workspaceId:connected.id,name:'Connected agent',key:'connected-agent',role:'Package',record:source})).json() as {stream:{id:string};snapshot:{id:string}};
    const hostedPath=`/api/release-intelligence/streams/${hosted.stream.id}`,hostedAccess=`${hostedPath}/agent-access`;
    const wrongSnap=await (await request(`${hostedPath}/records`,{record:neighbour})).json() as {snapshot:{id:string}};
    const hostedGrant=await (await request(hostedAccess,{...create,snapshotId:hosted.snapshot.id})).json() as {id:string;token:string};
    expect((await tool(hostedGrant.token,'get_release_evidence',{snapshotId:hosted.snapshot.id})).status).toBe(200);
    expect((await tool(hostedGrant.token,'compare_releases',{snapshotId:hosted.snapshot.id,previousSnapshotId:wrongSnap.snapshot.id})).status).toBe(409);
    await sql.query('UPDATE installations SET suspended=true WHERE id=994');expect((await tool(hostedGrant.token,'list_releases')).status).toBeGreaterThanOrEqual(400);
    await sql.query('UPDATE installations SET suspended=false WHERE id=994');expect((await tool(hostedGrant.token,'list_releases')).status).toBe(403);
    const renewed=await (await request(hostedAccess,{...create,snapshotId:hosted.snapshot.id})).json() as {id:string;token:string};expect((await tool(renewed.token,'list_releases')).status).toBe(200);
    await sql.query("UPDATE billing_accounts SET plan=NULL,trial_ends_at=now()-interval '1 day' WHERE installation_id=994");
    expect((await tool(renewed.token,'list_releases')).status).toBe(402);
    expect((await request(hostedAccess,{action:'revoke',grantId:renewed.id})).status).toBe(200);
  }finally{await sql.close();}
},60000);
