import { it, expect } from 'vitest';
import { openSql, migrate } from '../src/server/sql.ts';
import { createStore } from '../src/server/store.ts';
import { listUserWorkspaces } from '../src/server/workspaces.ts';

it('uses current workspace authority for package and custody removal', async () => {
  const sql = await openSql('pglite://:memory:');
  try {
    await migrate(sql);
    const store = createStore(sql, { tokenSecret: 'local-test-secret' });
    await store.upsertUser({ id: 'owner', login: 'owner' });
    await store.upsertInstallation({ id: 393, accountLogin: 'source', accountType: 'User', accountId: 393 });
    await store.linkUserInstallation(393, 'owner');
    const workspace = (await listUserWorkspaces(sql, 'owner')).find(w => Number(w.installation_id) === 393)!;
    await sql.query("UPDATE product_workspace_members SET role='admin',access_source='explicit' WHERE workspace_id=$1 AND user_id='owner'", [workspace.id]);
    await sql.query("DELETE FROM installation_users WHERE installation_id=393 AND user_id='owner'");
    const pkg = (await store.insertWatchedPackage(393, 'test-pack'))!;
    const oldGeneration = await store.packageConnectionGeneration(pkg.id,393);
    expect(oldGeneration).not.toBeNull();
    const map = await store.upsertMapDestination({ installationId: 393, kind: 'sentry', host: 'sentry.io', orgSlug: 'acme', projectSlug: 'app', token: 'fixture-token' });
    const oldCheck = (await store.getMapDestinationForCheck(map.id))!;
    expect(await store.setSourcePausedForUser('npm',pkg.id,'stranger',true)).toBe(false);
    expect(await store.setSourcePausedForUser('npm',pkg.id,'owner',true)).toBe(true);
    expect(await store.setSourcePausedForUser('npm',pkg.id,'owner',true)).toBe(true);
    expect((await sql.query("SELECT id FROM audit_events WHERE action='source.pause' AND target_kind='npm'")).rows).toHaveLength(1);
    expect(await store.packageConnectionGeneration(pkg.id,393)).toBeNull();
    expect(await store.listAllWatchedPackages()).toEqual([]);
    expect((await store.listSourceMonitoringForUser('owner',393)).find(row=>row.kind==='npm')?.paused).toBe(true);
    expect(await store.setSourcePausedForUser('npm',pkg.id,'owner',false)).toBe(true);
    expect(await store.setSourcePausedForUser('map',map.id,'owner',true)).toBe(true);
    expect(await store.getMapDestinationForCheck(map.id)).toBeNull();
    expect(await store.setSourcePausedForUser('map',map.id,'owner',false)).toBe(true);
    expect(await store.recordMapDestinationCheck(map.id,{status:'passed',error:null,fingerprint:'stale',configurationVersion:oldCheck.configurationVersion})).toBe(false);
    expect((await sql.query("SELECT id FROM audit_events WHERE action IN ('source.pause','source.resume')")).rows).toHaveLength(4);
    await migrate(sql);
    expect((await sql.query("SELECT id FROM audit_events WHERE action IN ('source.pause','source.resume')")).rows).toHaveLength(4);
    for (const role of ['viewer', 'member']) {
      await sql.query('UPDATE product_workspace_members SET role=$2 WHERE workspace_id=$1', [workspace.id, role]);
      expect(await store.deleteMapDestinationForUser(map.id, 'owner')).toBe(false);
      if (role === 'viewer') expect(await store.deleteWatchedPackageForUser(pkg.id, 'owner')).toBe(false);
    }
    await sql.query("UPDATE product_workspace_members SET role='admin' WHERE workspace_id=$1", [workspace.id]);
    await sql.query('UPDATE product_workspaces SET archived_at=now() WHERE id=$1', [workspace.id]);
    expect(await store.deleteWatchedPackageForUser(pkg.id, 'owner')).toBe(false);
    expect(await store.deleteMapDestinationForUser(map.id, 'owner')).toBe(false);
    await sql.query('UPDATE product_workspaces SET archived_at=NULL WHERE id=$1', [workspace.id]);
    await sql.query("INSERT INTO product_workspace_revocations(workspace_id,user_id) VALUES($1,'owner')", [workspace.id]);
    expect(await store.deleteWatchedPackageForUser(pkg.id, 'owner')).toBe(false);
    expect(await store.deleteMapDestinationForUser(map.id, 'owner')).toBe(false);
    await sql.query("DELETE FROM product_workspace_revocations WHERE workspace_id=$1 AND user_id='owner'", [workspace.id]);
    expect(await store.deleteWatchedPackageForUser(pkg.id, 'stranger')).toBe(false);
    expect(await store.deleteMapDestinationForUser(map.id, 'stranger')).toBe(false);
    expect(await store.deleteWatchedPackageForUser(pkg.id, 'owner')).toBe(true);
    expect(await store.deleteMapDestinationForUser(map.id, 'owner')).toBe(true);
    expect(await store.getWatchedPackage(pkg.id)).toBeNull();
    expect((await store.listMapIdentities(393)).some(row=>row.source==='package'&&row.id===pkg.id)).toBe(false);
    expect(await store.packageConnectionGeneration(pkg.id,393)).toBeNull();
    expect(await store.getMapDestination(map.id)).toBeNull();
    expect(await store.getMapDestinationAuth(map.id)).toBeNull();
    expect(await store.recordMapDestinationCheck(map.id,{status:'passed',error:null,fingerprint:'old',configurationVersion:oldCheck.configurationVersion})).toBe(false);
    expect((await store.listRetainedSourcesForUser('owner',393)).map(row=>row.kind).sort()).toEqual(['map','npm']);
    expect(await store.listRetainedSourcesForUser('stranger',393)).toEqual([]);
    expect(await store.listRetainedSourcesForUser('owner',999)).toEqual([]);
    expect((await sql.query('SELECT id FROM watched_packages WHERE id=$1 AND disconnected_at IS NOT NULL', [pkg.id])).rows).toHaveLength(1);
    expect((await sql.query('SELECT id FROM map_destinations WHERE id=$1 AND disconnected_at IS NOT NULL AND token_ciphertext IS NULL', [map.id])).rows).toHaveLength(1);
    expect((await store.insertWatchedPackage(393, 'test-pack'))?.id).toBe(pkg.id);
    expect(await store.packageConnectionGeneration(pkg.id,393)).not.toBe(oldGeneration);
    expect(await store.touchWatchedPackage(pkg.id,{version:'stale',connectionGeneration:oldGeneration!})).toBe(false);
    expect((await store.getWatchedPackage(pkg.id))?.last_version).not.toBe('stale');
    await expect(store.insertPackageIdentitySnapshot({installationId:393,packageId:pkg.id,connectionGeneration:oldGeneration!,maintainers:[],binNames:[],lifecycleScripts:[]})).rejects.toThrow('connection changed');
    expect(await store.recordWatchedPackageScan(pkg.id,{sha256:'stale',status:'passed',connectionGeneration:oldGeneration!})).toBe(false);
    expect(await store.recordPackageMapIdentity(pkg.id,{debugIds:['stale'],release:'stale',publicMap:true,connectionGeneration:oldGeneration!})).toBe(false);
    expect((await store.getWatchedPackage(pkg.id))?.last_sha256).not.toBe('stale');
    await expect(store.insertAlert({installationId:393,kind:'npm_scan',title:'stale',body:'stale',packageConnection:{id:pkg.id,generation:oldGeneration!}})).rejects.toThrow('connection changed');
    expect((await sql.query("SELECT id FROM alerts WHERE title='stale'")).rows).toEqual([]);
    expect(await store.packageConnectionGeneration(pkg.id,999)).toBeNull();
    expect((await store.upsertMapDestination({ installationId: 393, kind: 'sentry', host: 'sentry.io', orgSlug: 'acme', projectSlug: 'app', token: 'replacement-token' })).id).toBe(map.id);
    expect(await store.getWatchedPackage(pkg.id)).not.toBeNull();
    expect((await store.listMapIdentities(393)).some(row=>row.source==='package'&&row.id===pkg.id)).toBe(true);
    expect((await store.getMapDestinationAuth(map.id))?.token).toBe('replacement-token');
    expect(await store.recordMapDestinationCheck(map.id,{status:'passed',error:null,fingerprint:'old',configurationVersion:oldCheck.configurationVersion})).toBe(false);
    expect((await store.getMapDestination(map.id))?.last_status).toBeNull();
    await expect(store.insertAlert({installationId:393,kind:'map_custody_check',title:'stale custody',body:'stale',custodyConnection:{id:map.id,configurationVersion:oldCheck.configurationVersion}})).rejects.toThrow('connection changed');
    const newCheck = (await store.getMapDestinationForCheck(map.id))!;
    expect(await store.recordMapDestinationCheck(map.id,{status:'passed',error:null,fingerprint:'current',configurationVersion:newCheck.configurationVersion})).toBe(true);
    expect(await store.listRetainedSourcesForUser('owner',393)).toEqual([]);
    // Replacing credentials or reconnecting must not silently undo an explicit pause.
    expect(await store.setSourcePausedForUser('npm',pkg.id,'owner',true)).toBe(true);
    expect(await store.setSourcePausedForUser('map',map.id,'owner',true)).toBe(true);
    await store.deleteWatchedPackageForUser(pkg.id,'owner');
    await store.deleteMapDestinationForUser(map.id,'owner');
    expect((await store.insertWatchedPackage(393,'test-pack'))?.id).toBe(pkg.id);
    expect((await store.upsertMapDestination({installationId:393,kind:'sentry',host:'sentry.io',orgSlug:'acme',projectSlug:'app',token:'new-token'})).id).toBe(map.id);
    expect((await store.listSourceMonitoringForUser('owner',393)).every(row=>row.paused)).toBe(true);
    expect(await store.packageConnectionGeneration(pkg.id,393)).toBeNull();
    expect(await store.getMapDestinationForCheck(map.id)).toBeNull();
    expect(await store.setSourcePausedForUser('npm',pkg.id,'owner',false)).toBe(true);
    expect(await store.setSourcePausedForUser('map',map.id,'owner',false)).toBe(true);
    expect(await store.packageConnectionGeneration(pkg.id,393)).not.toBeNull();
    expect(await store.getMapDestinationForCheck(map.id)).not.toBeNull();
  } finally { await sql.close(); }
});
