import {it,expect} from 'vitest';
import {openSql,migrate} from '../src/server/sql.ts';
import {createStore,signSession} from '../src/server/store.ts';
import {createApp} from '../src/server/app.ts';
import {loadConfig} from '../src/server/config.ts';
import {stubGithub} from '../src/server/stub-github.ts';
import {workspaceOverview} from '../src/server/workspace-overview.ts';
import {workspaceCoverageSummary} from '../src/server/workspace-coverage-summary.ts';
it('includes connected release evidence without counting uploaded revisions twice',async()=>{
 const sql=await openSql('pglite://:memory:');try{
  await migrate(sql);const store=createStore(sql);await store.upsertUser({id:'owner',login:'owner'});
  await store.upsertInstallation({id:7,accountId:7,accountLogin:'owner',accountType:'User'});await store.linkUserInstallation(7,'owner');
  const workspace=(await sql.query<{workspace_id:string}>('SELECT workspace_id FROM product_workspace_installations WHERE installation_id=7')).rows[0].workspace_id;
  const pkg=(await store.insertWatchedPackage(7,'coverage-test'))!;
  expect(await workspaceCoverageSummary(sql,workspace,60000)).toEqual({total:1,paused:0,unavailable:0,unknown:1,delayed:0,recent:0,connections:[{installationId:7,name:'owner'}],sources:[{key:`npm-${pkg.id}`,name:'coverage-test',installationId:7,connectionName:'owner',health:'unknown'}]});
  const now=Date.parse('2026-09-08T12:00:00Z');
  await sql.query("UPDATE watched_packages SET last_checked_at='2026-09-08T11:59:30Z' WHERE id=$1",[pkg.id]);
  expect((await workspaceCoverageSummary(sql,workspace,60000,now)).recent).toBe(1);
  await sql.query("UPDATE watched_packages SET last_checked_at='2026-09-08T11:57:00Z' WHERE id=$1",[pkg.id]);
  expect((await workspaceCoverageSummary(sql,workspace,60000,now)).delayed).toBe(1);
  await sql.query("UPDATE watched_packages SET last_checked_at='2026-09-08T12:01:00Z' WHERE id=$1",[pkg.id]);
  expect((await workspaceCoverageSummary(sql,workspace,60000,now)).unknown).toBe(1);
  expect((await workspaceCoverageSummary(sql,workspace,NaN,now)).unknown).toBe(1);
  await sql.query('UPDATE installations SET suspended=true WHERE id=7');
  expect((await workspaceCoverageSummary(sql,workspace,60000)).unavailable).toBe(1);
  await sql.query('UPDATE installations SET suspended=false WHERE id=7');
  await sql.query('UPDATE watched_packages SET paused_at=now() WHERE id=$1',[pkg.id]);
  expect((await workspaceCoverageSummary(sql,workspace,60000)).paused).toBe(1);
  await sql.query('UPDATE watched_packages SET disconnected_at=now() WHERE id=$1',[pkg.id]);
  expect((await workspaceCoverageSummary(sql,workspace,60000)).total).toBe(0);
  await sql.query("INSERT INTO map_destinations(installation_id,kind,host,org_slug,project_slug,token_ciphertext,last_checked_at,last_status) VALUES(7,'sentry','sentry.io','org','project','test-only','2026-09-08T11:59:00Z','inconclusive')");
  expect(await workspaceCoverageSummary(sql,workspace,60000,now)).toMatchObject({total:1,unknown:1,recent:0});
  await sql.query("UPDATE map_destinations SET last_status='passed' WHERE installation_id=7");
  expect(await workspaceCoverageSummary(sql,workspace,60000,now)).toMatchObject({total:1,unknown:0,recent:1});
  await sql.query("UPDATE map_destinations SET disconnected_at=now(),token_ciphertext=NULL WHERE installation_id=7");
  await sql.query("INSERT INTO watched_origins(installation_id,origin_url,host,verification_token,last_checked_at) VALUES(7,'https://example.com','example.com','pending-proof',now())");
  expect((await workspaceCoverageSummary(sql,workspace,60000)).unknown).toBe(1);
  await sql.query("UPDATE watched_origins SET verified_at=now() WHERE installation_id=7");
  expect((await workspaceCoverageSummary(sql,workspace,60000)).unknown).toBe(1);
  await sql.query("UPDATE watched_origins SET last_scan_status='inconclusive' WHERE installation_id=7");
  expect((await workspaceCoverageSummary(sql,workspace,60000)).unknown).toBe(1);
  await sql.query("UPDATE watched_origins SET last_scan_status='passed' WHERE installation_id=7");
  expect((await workspaceCoverageSummary(sql,workspace,60000)).recent).toBe(1);
  await sql.query("UPDATE watched_origins SET last_scan_status='failed-policy' WHERE installation_id=7");
  expect((await workspaceCoverageSummary(sql,workspace,60000)).recent).toBe(1);
  await sql.query("UPDATE watched_origins SET disconnected_at=now() WHERE installation_id=7");
  const receipt=(await sql.query<{id:number}>("INSERT INTO scan_receipts(installation_id,coordinate,status,engine_version,manifest,finding_fingerprints,signature,receipt) VALUES(7,'test','passed','test','[]','[]','test','{}') RETURNING id")).rows[0].id;
  const revision=await store.insertReleaseRevision({installationId:7,receiptId:receipt,coordinate:'test',channel:'stable',artifactSha256:'hash',mismatch:false});
  expect((await workspaceOverview(sql,'owner',workspace)).hostedReleases).toEqual({total:1,passed:1,attention:0});
  expect((await store.listReleaseRevisionsForUser('owner',{installationId:7,hostedDecision:'passed'})).length).toBe(1);
  expect((await store.listReleaseRevisionsForUser('owner',{installationId:7,hostedDecision:'attention'})).length).toBe(0);
  expect((await workspaceOverview(sql,'owner',workspace)).hostedSources).toEqual([{installationId:7,name:'owner',total:1,passed:1,attention:0}]);
  const app=createApp({store,github:stubGithub(),config:loadConfig({sessionSecret:'test'})});
  const headers={cookie:`ns_session=${signSession('test',await store.createSession('owner'))}`};
  expect((await app.request(`/api/releases?installationId=7&hostedDecision=passed&workspace=${workspace}`,{headers})).status).toBe(200);
  expect((await app.request('/api/releases?installationId=7&hostedDecision=passed&workspace=wrong',{headers})).status).toBe(404);
  expect((await app.request(`/api/releases?installationId=999&hostedDecision=passed&workspace=${workspace}`,{headers})).status).toBe(404);
  await store.upsertInstallation({id:701,accountId:701,accountLogin:'other-owned',accountType:'User'});
  await store.linkUserInstallation(701,'owner');
  expect((await app.request(`/api/releases?installationId=701&hostedDecision=passed&workspace=${workspace}`,{headers})).status).toBe(404);
  await sql.query("INSERT INTO uploaded_scans(id,user_id,workspace_id,installation_id,target,artifact_sha256,status,revision_id,report_json) VALUES('upload','owner',$1,7,'test','hash','done',$2,'{\"ok\":true,\"status\":\"passed\"}')",[workspace,revision.id]);
  const result=await workspaceOverview(sql,'owner',workspace);
  expect(result.hostedReleases).toEqual({total:0,passed:0,attention:0});expect(result.counts.total).toBe(1);
  expect(await store.listReleaseRevisionsForUser('owner',{installationId:7,hostedDecision:'all'})).toHaveLength(0);
  await store.insertReleaseRevision({installationId:7,receiptId:receipt,coordinate:'changed',channel:'stable',artifactSha256:'different',mismatch:true});
  expect((await workspaceOverview(sql,'owner',workspace)).hostedReleases).toEqual({total:1,passed:0,attention:1});
  const reviewRows=await store.listReleaseRevisionsForUser('owner',{installationId:7,hostedDecision:'attention'});
  expect(reviewRows).toHaveLength(1);
  expect(await store.listReleaseRevisionsForUser('owner',{installationId:7,hostedDecision:'attention',before:reviewRows[0].id})).toHaveLength(0);
  expect(await store.listReleaseRevisionsForUser('stranger',{installationId:7,hostedDecision:'all'})).toHaveLength(0);
  await store.upsertInstallation({id:8,accountId:8,accountLogin:'foreign',accountType:'User'});
  await store.insertWatchedPackage(8,'foreign-only');
  expect((await workspaceCoverageSummary(sql,workspace,60000)).total).toBe(0);
  await store.upsertInstallation({id:9,accountId:9,accountLogin:'second',accountType:'User'});
  await sql.query('INSERT INTO product_workspace_installations(installation_id,workspace_id) VALUES(9,$1) ON CONFLICT(installation_id) DO UPDATE SET workspace_id=$1',[workspace]);
  await store.insertWatchedPackage(9,'second-package');
  await sql.query('UPDATE watched_packages SET disconnected_at=NULL,paused_at=NULL,last_checked_at=now() WHERE id=$1',[pkg.id]);
  await sql.query('UPDATE installations SET suspended=true WHERE id=9');
  const mixed=await workspaceCoverageSummary(sql,workspace,60000);
  expect(mixed.total).toBe(2);
  expect(mixed.recent).toBe(1);
  expect(mixed.unavailable).toBe(1);
  expect(mixed.connections).toEqual([{installationId:7,name:'owner'},{installationId:9,name:'second'}]);
  await sql.query(`INSERT INTO jobs(installation_id,priority,kind,payload,status) VALUES
   (7,'heavy','release_scan','{}','queued'),(7,'heavy','npm_scan','{}','running'),
   (7,'heavy','uploaded_scan','{}','queued'),(7,'heavy','workspace_origin_scan','{}','running'),
   (7,'light','member_added','{}','queued'),(7,'heavy','release_scan','{}','done'),
   (8,'heavy','release_scan','{}','queued')`);
  expect((await workspaceOverview(sql,'owner',workspace)).connectedActivity).toEqual([{installationId:7,name:'owner',queued:1,running:1}]);
 }finally{await sql.close();}
});
