import {it,expect} from 'vitest';
import {migrate,openSql} from '../src/server/sql.ts';
import {createStore} from '../src/server/store.ts';
import {ensureUserWorkspaces,listUserWorkspaces} from '../src/server/workspaces.ts';
import {createWorkspaceOrigin,verifyWorkspaceOrigin} from '../src/server/workspace-origins.ts';
import {processUploadedScan} from '../src/server/upload-worker.ts';
import {scan} from '../src/scanner/index.ts';
import {saveWorkspaceNotification} from '../src/server/workspace-notifications.ts';
import {runWorkspaceNotification} from '../src/server/workspace-notification-worker.ts';
import {randomUUID} from 'node:crypto';
import {requestWorkspaceException,decideWorkspaceException} from '../src/server/workspace-exceptions.ts';
it('queues a verified website against the existing payer and saves a real workspace result without GitHub',async()=>{
 const sql=await openSql('pglite://:memory:');try{
  await migrate(sql);const store=createStore(sql);await store.upsertUser({id:'owner',login:'owner'});await ensureUserWorkspaces(sql,'owner');
  const workspace=(await listUserWorkspaces(sql,'owner'))[0];
  const origin=await createWorkspaceOrigin(sql,'owner',workspace.id,'https://example.com');
  const input={id:'website-attempt',userId:'owner',installationId:null,workspaceId:workspace.id,target:origin.origin_url,bytes:new Uint8Array(),sourceOriginId:origin.id,meta:{coordinate:`web:${origin.origin_url}`}};
  await expect(store.queueUploadedScan(input)).rejects.toMatchObject({status:409});
  await verifyWorkspaceOrigin(sql,'owner',workspace.id,origin.id,'dns',async(_host,_token,method)=>({method,detail:'matched'}));
  await store.queueUploadedScan(input);
  expect((await sql.query('SELECT kind,billing_user_id,installation_id FROM jobs')).rows).toEqual([{kind:'workspace_origin_scan',billing_user_id:'owner',installation_id:null}]);
  await processUploadedScan(input.id,store,scan,'test-signing',undefined,{lookup:async()=>[{address:'1.1.1.1',family:4}],fetch:async url=>String(url)==='https://example.com/'?new Response('<html><body>Hello</body></html>',{headers:{'content-type':'text/html'}}):new Response('missing',{status:404})});
  const result=await store.getUploadedScan('owner',input.id);expect(result?.status).toBe('done');expect(result?.receipt_json).not.toBeNull();expect(result?.artifact_sha256).toHaveLength(64);
  expect(await store.queueUploadedScan(input)).toBe(input.id);
  expect((await sql.query('SELECT * FROM installations')).rows).toHaveLength(0);
  expect((await sql.query<{scans:number}>('SELECT scans FROM personal_scan_usage')).rows).toEqual([{scans:1}]);
  expect((await sql.query('SELECT id FROM alerts')).rows).toHaveLength(0);
  const flagged={...input,id:'website-finding'};
  await saveWorkspaceNotification(sql,'owner',workspace.id,'email','owner@example.com','notification-key');
  await store.queueUploadedScan(flagged);
  const finding={rule:'MAP-001',severity:'critical' as const,path:'app.js.map',title:'Public source map',detail:'Original source exposed'};
  const scanWithFinding:typeof scan=async(...args)=>({...await scan(...args),findings:[finding],ok:false,status:'failed-policy'});
  const webOptions={lookup:async()=>[{address:'1.1.1.1',family:4}],fetch:async()=>new Response('<html>Hello</html>',{headers:{'content-type':'text/html'}})};
  await processUploadedScan(flagged.id,store,scanWithFinding,'test-signing',undefined,webOptions);
  const alerts=await sql.query('SELECT workspace_id,installation_id,source_origin_id,scan_attempt_id,findings,resolved_at FROM alerts');
  expect(alerts.rows).toEqual([{workspace_id:workspace.id,installation_id:null,source_origin_id:origin.id,scan_attempt_id:flagged.id,findings:[finding],resolved_at:null}]);
  await processUploadedScan(flagged.id,store,scanWithFinding,'test-signing',undefined,webOptions);
  expect((await sql.query('SELECT id FROM alerts')).rows).toHaveLength(1);
  expect((await sql.query('SELECT id FROM workspace_notification_jobs')).rows).toHaveLength(1);
  let delivered=0;
  await runWorkspaceNotification(sql,{encryptionSecret:'notification-key',emailApiKey:'mock-key',emailFrom:'service@example.com',fetch:async(_url,options)=>{
    delivered++;expect(String(options?.body)).not.toContain('Original source exposed');return new Response('ok');
  }});
  expect(delivered).toBe(1);
  expect((await sql.query('SELECT status,alert_id FROM notification_deliveries')).rows).toHaveLength(1);
  expect((await sql.query('SELECT resolved_at FROM alerts')).rows).toEqual([{resolved_at:null}]);
  const original=await store.getUploadedScan('owner',flagged.id);
  const exception=await requestWorkspaceException(sql,'owner',workspace.id,{requestKey:randomUUID(),attemptId:flagged.id,findingIndex:0,reason:'Explicit risk acceptance for this website only',expiresAt:new Date(Date.now()+86400000).toISOString()});
  await decideWorkspaceException(sql,'owner',workspace.id,exception.id,'approved','Administrator reviewed the exact website scope');
  const recheck={...input,id:'website-exception-recheck'};await store.queueUploadedScan(recheck);
  await processUploadedScan(recheck.id,store,scanWithFinding,'test-signing',undefined,webOptions);
  expect((await store.getUploadedScan('owner',recheck.id))?.report_json).toMatchObject({status:'passed',findings:[],suppressed:[{finding}]});
  expect((await sql.query('SELECT resolved_at FROM alerts')).rows).toEqual([{resolved_at:null}]);
  expect((await sql.query('SELECT id FROM workspace_notification_jobs')).rows).toHaveLength(1);
  const other=await createWorkspaceOrigin(sql,'owner',workspace.id,'https://other.example.com');
  await verifyWorkspaceOrigin(sql,'owner',workspace.id,other.id,'dns',async(_host,_token,method)=>({method,detail:'matched'}));
  const otherCheck={...input,id:'other-website-check',sourceOriginId:other.id,target:other.origin_url};await store.queueUploadedScan(otherCheck);
  await processUploadedScan(otherCheck.id,store,scanWithFinding,'test-signing',undefined,webOptions);
  expect((await store.getUploadedScan('owner',otherCheck.id))?.report_json).toMatchObject({status:'failed-policy',findings:[finding],suppressed:[]});
  expect((await store.getUploadedScan('owner',flagged.id))?.report_json).toEqual(original?.report_json);
  expect((await store.getUploadedScan('owner',flagged.id))?.receipt_json).toEqual(original?.receipt_json);
  await sql.query('INSERT INTO product_workspace_revocations(workspace_id,user_id) VALUES($1,$2)',[workspace.id,'owner']);
  expect(await store.getUploadedScan('owner',input.id)).toBeNull();
 }finally{await sql.close();}
});
