import {assessmentFixture} from './assessment-fixtures';
import {HostedBriefFixture} from './HostedBriefFixture';
import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {HostedReleaseEvidence} from '../../src/components/watch/HostedReleaseEvidence';
import {WorkspaceTokens} from '../../src/components/watch/WorkspaceTokens';
import {WorkspaceEvidenceSettings} from '../../src/components/watch/WorkspaceEvidenceSettings';
import './app-styles.css';
import '../../src/components/watch/design/app-system.css';
import './review.css';
type Mode='tokens'|'readonly'|'audit'|'error'|'hosted'|'brief'|'brief-ready'|'brief-review'|'brief-blocked';
let mode:Mode='tokens';
// Every request is resolved here. There is deliberately no network fallback.
window.fetch=async(input,init)=>init?.method&&init.method!=='GET'?Response.json({error:'Fixture mutations are disabled.'},{status:405}):mode.startsWith('brief-')&&String(input).includes('/api/assurance/')?Response.json({view:assessmentFixture(mode)}):(mode==='hosted'||mode.startsWith('brief'))?Response.json(String(input).endsWith('/evidence')?{available:true,workspaceId:'fixture',report:{findings:mode==='brief-review'?[{rule:'MAP-002',severity:'warn',path:'bundle.js.map',title:'Map',detail:'Fixture: warning requires review.'}]:mode.startsWith('brief-')?[]:[{rule:'MAP-001',severity:'critical',path:'packages/example-release/production/assets/long-artifact-name.js.map',title:'Source map in saved artifact',detail:'Fixture: this source map was recorded in the selected artifact.'},{rule:'DOC-001',severity:'warn',path:'internal/build-notes/release-documentation.md',title:'Internal documentation in saved artifact',detail:'Fixture: internal documentation was recorded in the selected artifact.'}],suppressed:[]}}:String(input).endsWith('/exceptions')?{canRequest:true}:{error:'Fixture: supporting assurance unavailable.'},{status:String(input).endsWith('/evidence')||String(input).endsWith('/exceptions')?200:503}):Response.json(mode==='error'?{error:'Fixture: access is unavailable. Retry after access is restored.'}:mode==='audit'?{
 workspace:{name:'Fixture workspace',organization_id:'fixture',role:'viewer',organization_owner:false},retention:{savedScans:4,activeScans:0},nextCursor:null,
 events:[{id:'1',action:'workspace_created',actor:'example-owner-with-a-long-account-name',created_at:'2026-09-09T12:00:00Z'},{id:'2',action:'member_role_changed',actor:null,created_at:'2026-09-09T12:30:00Z'}],
}:{tokens:[{id:1,name:'CI — release-package-with-a-long-integration-name',token_prefix:'fixture_only',revoked_at:null,last_used_at:'2026-09-09T12:00:00Z'},{id:2,name:'Retired build integration',token_prefix:'fixture_only',revoked_at:'2026-09-08T12:00:00Z',last_used_at:null}],nextCursor:null,canManage:mode!=='readonly'}, {status:mode==='error'?403:200});
function HostedFixture(){const [search,setSearch]=useState('?workspace=fixture&releaseFinding=0');useEffect(()=>{const update=()=>setSearch(location.search);window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update);},[]);return <HostedReleaseEvidence releaseId={1} receiptId={1} search={search}/>;}
function Review(){const [selected,setSelected]=useState<Mode>('tokens');return <><aside className="fixture-toolbar"><strong>ISOLATED UI FIXTURES · NOT CUSTOMER DATA</strong><p>Actual components, local responses. No customer API or credentials. Mutation outcomes are not simulated.</p><div role="group" aria-label="Review state">{([['tokens','Populated tokens'],['readonly','Read-only tokens'],['audit','Populated audit'],['error','Access error'],['hosted','Hosted findings'],['brief','Hosted brief'],['brief-ready','Ready assessment'],['brief-review','Review assessment'],['brief-blocked','Blocked assessment']] as const).map(([value,label])=><button key={value} aria-pressed={selected===value} onClick={()=>{mode=value;setSelected(value);}}>{label}</button>)}</div></aside><main className="watch-desk fixture-page" key={selected}>{selected.startsWith('brief')?<HostedBriefFixture mode={selected}/>:selected==='hosted'?<HostedFixture/>:selected==='audit'?<WorkspaceEvidenceSettings workspaceId="fixture" view="audit"/>:<WorkspaceTokens workspaceId="fixture"/>}</main></>}
createRoot(document.getElementById('root')!).render(<Review/>);
