import {asFindingList} from './format.ts';

export type Explanation = {title:string;meaning:string;action:string;verify:string};
const explain=(title:string,meaning:string,action:string,verify:string):Explanation=>({title,meaning,action,verify});
const rescan='Rebuild and scan the exact artifact customers receive. Review the new saved result; resolving this alert does not prove the fix.';
export const ruleExplanations:Record<string,Explanation>={
 'MAP-001':explain('Source map included','The inspected artifact contains a source-map file. Maps can reveal source structure even without embedded source.','Exclude public .map files from the production package. Upload maps privately to your error tracker if needed; hidden source-map mode alone can still leave .map files in the package.',rescan),
 'MAP-002':explain('Original source embedded in a map','The map includes original source content, which recipients of this artifact can read.','Remove the public map from the shipped artifact and keep required debugging maps in private storage.',rescan),
 'MAP-003':explain('Source-map reference in a production file','A sourceMappingURL comment points to a map or contains an inline map. An external reference alone does not prove the referenced map was accessible.','Disable public source-map references and inline maps in production output. Check whether the referenced map is also shipped or publicly served.',rescan),
 'MAP-011':explain('Private source map missing','The custody check did not find a matching map in the configured private provider. This is a debugging coverage gap, not proof of public exposure.','Check provider project, release and debug identifiers, upload the matching map privately, and confirm read access.','Rerun Map custody for the same release identity and review its saved result.'),
 'MAP-012':explain('Map still publicly accessible','The custody check found a public map despite private map custody being configured. A private copy does not remove the public copy.','Remove the map from public deployment output and invalidate the affected CDN cache. Retain the private debugging copy.','Rerun custody and the verified website check; confirm the public URL is no longer serving the map.'),
 'SEC-001':explain('Environment file included','An environment file was detected in the inspected content. Its presence alone does not establish that every value is a live secret.','Inspect values locally without sharing them. Exclude private environment files from packaging. If real credentials were exposed, revoke or rotate them; deleting the file alone is insufficient.',rescan),
 'SEC-002':explain('Private key material detected','The check flagged a private-key file or pattern. The scanner does not test whether the key is active.','Inspect locally. Remove private keys from release output and replace exposed active keys through the owning service. Never paste key material into an agent prompt.',rescan),
 'SEC-003':explain('Credential pattern detected','The check matched a supported credential or token pattern. It does not authenticate with that credential or establish whether it is active.','Validate the match locally. Revoke or rotate genuine exposed credentials and move them to server-side secret storage; do not send their values to an AI agent.',rescan),
 'SEC-004':explain('Credential configuration included','Credential-related configuration was detected. Review whether it contains real credentials rather than assuming a filename proves a leak.','Exclude private credential configuration from distribution. Rotate exposed active credentials and retain only intentionally public placeholders.',rescan),
 'AI-001':explain('AI instructions or context included','The inspected content includes a file or pattern associated with agent instructions, prompts or memory. Some such files may be intentionally public.','Review whether this context belongs in the customer artifact. Keep private prompts, memory and tool configuration out of release packaging.',rescan),
 'NET-001':explain('Internal location detected','An internal endpoint or developer path was detected. This does not prove the endpoint is reachable or vulnerable.','Review the recorded path or endpoint locally and remove private environment details from public output.',rescan),
 'DBG-001':explain('Debug metadata included','Debug or build metadata was found in the inspected artifact. It can disclose implementation details.','Exclude development-only debug output from the production package, or document why the specific file is intentionally distributed.',rescan),
 'CACHE-001':explain('Build cache included','Compiler or bundler cache files were found. Caches can retain paths and intermediate source content.','Package from a clean output directory and exclude compiler and bundler caches.',rescan),
 'CRASH-001':explain('Crash dump included','A crash or core dump was detected. Dumps can contain process memory and sensitive runtime data.','Remove dumps from distribution and inspect them only in a controlled local environment. Assess whether exposed credentials require rotation.',rescan),
 'GIT-001':explain('Git metadata included','The artifact contains Git metadata, which can expose repository history beyond the intended release.','Exclude .git directories and package only the intended build output.',rescan),
 'SRC-001':explain('Original source included','TypeScript or JSX source was found in the artifact. This may be intentional for a source-distributed library; it is not automatically a vulnerability.','Check your distribution contract. Exclude private source from compiled-only packages, or review an appropriately scoped policy exception for intended source distribution.',rescan),
 'SIZE-001':explain('Unexpectedly large file','An inspected file exceeded the scanner’s normal size baseline. Size alone is not evidence of malicious content.','Inspect the file and packaging changes; remove accidental data dumps, generated copies or bundled dependencies.',rescan),
 'SIZE-002':explain('Unexpectedly large artifact','The artifact exceeded the normal size baseline. This is a packaging signal, not a malware verdict.','Compare package contents against the intended release and investigate large additions.',rescan),
 'SIZE-003':explain('Unpacked size increased','Recorded unpacked size increased against a previous or approved scan. The increase needs review, not an automatic compromise conclusion.','Compare the two release file inventories and explain intentional additions before adopting a new reference.',rescan),
 'ARC-001':explain('Nested archive included','The inspected package contains another archive. Review its contents and the saved scan scope; do not assume every nested payload was inspected.','Remove accidental nested packages, or scan intended nested artifacts separately when the recorded scope does not cover them.',rescan),
 'ARC-002':explain('Archive path escapes its boundary','An archive entry uses a path that escapes the package boundary. Unsafe extraction could write outside its destination.','Do not extract it without safeguards. Recreate the archive with safe relative entry paths; keep scanner isolation and extraction guards enabled.',rescan),
 'LNK-001':explain('Link escapes the package','A symbolic link points outside the artifact boundary. Its target is outside the intended inspection scope.','Replace the escaping link with intended packaged content or remove it. Do not weaken extraction safeguards.',rescan),
 'BAK-001':explain('Backup copy included','A backup file was detected. Backups can preserve data or source that was removed from the current file.','Exclude backups and inspect the copy locally for private content or credentials.',rescan),
 'DB-001':explain('Database material included','A database dump or database file was detected. The finding does not establish whether it contains real customer data.','Inspect locally, remove unintended data from packaging, and assess any actual data exposure through your incident process.',rescan),
 'DOC-001':explain('Internal document included','A file or pattern associated with internal product documents was detected. Review whether it was intended for recipients.','Exclude private roadmaps, handoffs and product documents from the package; retain only intended public documentation.',rescan),
};
const reviewEvent='Confirm the current state in the source service and review a fresh applicable check. Acknowledging or resolving this alert only records your response.';
const event=(title:string,meaning:string,action:string)=>explain(title,meaning,action,reviewEvent);
export const kindExplanations:Record<string,Explanation>={
 repo_publicized:event('Repository became public','GitHub recorded a private repository becoming public. This records visibility at the event time, not its current state or proof that someone copied it.','Confirm whether publication was intended. If not, have an authorised owner restore the intended visibility and assess exposed history and credentials.'),
 repo_created_public:event('Repository created public','GitHub recorded a new public repository. Public visibility may be intentional.','Check the intended visibility and review its contents before continuing to publish.'),
 repo_transferred:event('Repository ownership changed','GitHub recorded a repository transfer. A transfer does not itself prove compromise.','Confirm the destination owner, repository visibility, collaborators and app access are intended.'),
 member_added:event('Collaborator added','GitHub recorded a collaborator being granted repository access. This is an access change, not a finding in a release artifact.','Confirm the person and role with the repository owner. Remove unapproved access through GitHub and review the audit trail.'),
 fork:event('Repository forked','GitHub recorded a fork. This does not establish that private credentials were exposed, and changing the original repository cannot recall existing copies.','Review who owns the fork and whether the source was intended to be shared. Investigate actual sensitive content before taking containment action.'),
 repos_added:event('More repositories connected','The GitHub App gained access to additional repositories. Connection is not evidence that their release artifacts have been scanned.','Review the newly visible repositories in Coverage and choose the release checks you want to run.'),
 repos_removed:event('Repository access removed','Repositories were removed from the GitHub App installation. New checks may no longer have access; saved evidence remains historical.','Confirm removal was intended, or restore the specific repository access in GitHub installation settings.'),
 app_suspended:event('GitHub App suspended','GitHub suspended the installation, preventing normal access for its checks. Existing scan results do not establish current coverage.','Ask the installation owner to review the suspension and restore access if appropriate.'),
 app_unsuspended:event('GitHub App resumed','GitHub reported that the installation was resumed. Resuming access does not establish that a new scan passed.','Review Coverage and run the relevant release check to obtain fresh evidence.'),
 app_permissions_updated:event('GitHub App permissions changed','GitHub reported an installation permission change. Capabilities depend on the permissions actually granted.','Review the requested permissions and the installation’s approved access before using affected actions.'),
 repo_made_private:event('Repository made private','A visibility change was recorded. Making a repository private does not recall prior public copies or prove exposed credentials are safe.','Confirm current visibility and separately review any previously exposed credentials or release assets.'),
 release_assets_removed:event('Release assets removed','Release asset removal was recorded. Previously downloaded copies may still exist.','Check which assets were removed and publish a reviewed replacement if needed; assess prior exposure separately.'),
 workflow_disabled:event('Workflow disabled','A GitHub workflow was disabled. This stops that workflow, not all publication paths.','Confirm the intended containment action and review other publishing paths before re-enabling a corrected workflow.'),
 release_deleted:event('Release deleted','GitHub recorded a release deletion. Saved evidence describes the former release, not a current downloadable asset.','Confirm the deletion was intended and locate or publish the intended replacement.'),
 release_unpublished:event('Release unpublished','GitHub recorded a release being unpublished. This does not revoke copies already downloaded.','Review release visibility and any replacement before publishing again.'),
 npm_dist_tag:event('npm distribution tag moved','An npm tag now points to a different version. Consumers using that tag may receive different bytes; this is not by itself compromise.','Check the old and new version in the recorded event, confirm the publisher’s intent, and scan the version now served by the tag.'),
 package_unpublished:event('npm package unpublished','The watched npm package or version became unavailable. Existing consumer caches may still contain it.','Confirm the registry state and intended replacement, then review consumers pinned to the unavailable version.'),
 package_maintainer_changed:event('npm maintainers changed','The package’s maintainer list changed. This is an ownership continuity signal, not a malware verdict.','Verify added and removed maintainers with the package owner and review subsequent published versions.'),
 package_publisher_changed:event('Package publisher changed','The recorded publisher identity changed from the previous observation. An authorised release process change can explain this.','Confirm the publishing account and release pipeline with the package owner, then inspect the new artifact.'),
 package_repository_mismatch:event('Package repository field changed','The package metadata now names a different repository. Metadata alone does not prove where the bytes were built.','Compare the recorded old and new coordinates with the intended repository and confirm the change with the owner.'),
 package_homepage_mismatch:event('Package homepage changed','The package metadata homepage changed. This is a metadata change, not proof of compromise.','Verify that the new domain is the intended project site; review other identity changes in the same release.'),
 package_shape_anomaly:event('Package executable or script surface changed','Package metadata reported new executable entries or lifecycle scripts. Such scripts may run in consumer environments.','Inspect the added bin entries and install scripts without running untrusted code; confirm each change is intended.'),
 identity_lookalike_registered:event('Similar package name registered','A package with a similar name was observed. Similarity does not prove impersonation or malicious intent.','Verify exact package names in manifests and lockfiles. Investigate ownership before changing dependencies or making a report.'),
 identity_lookalike_version:event('Similar package published a version','A similar-name package published a version. Name similarity does not prove impersonation or unsafe code.','Check exact dependency coordinates and ownership before adopting the package or making a report.'),
 identity_burst:event('Publishing activity increased','The observed publishing rate increased. A release burst may be an intended automation or maintenance change.','Confirm publisher identity and release cadence with the owner, then inspect relevant package versions.'),
 identity_size_jump:event('Registry reports a size increase','npm metadata claims a larger unpacked size. This is a registry-reported figure, not a measurement from a downloaded artifact.','Compare versions and inspect the actual package contents to explain the growth.'),
 identity_new_dependency:event('New dependency observed','The recorded package metadata added a dependency. This alone is not proof that it is unsafe.','Review the exact dependency name, version range and purpose; inspect the lockfile and release artifact.'),
 identity_dormant:event('Dormant package became active','Publishing activity resumed after a recorded quiet period. This can be legitimate maintenance.','Confirm the new publisher and release intent, and review what changed in the new version.'),
 identity_jump:event('Package version pattern changed','A version change triggered an identity signal. Version numbering alone does not establish compromise.','Compare the recorded versions, release notes and publisher identity before adopting the new version.'),
 identity_provenance_lost:event('Provenance metadata disappeared','The registry no longer lists previously observed attestations. No attestation signature was verified by this presence check.','Review the publishing workflow and provenance configuration; verify any attestation through an appropriate trusted verifier.'),
 identity_provenance_changed:event('Provenance metadata changed','The registry’s recorded provenance predicate changed. This is metadata, not verified build provenance.','Confirm the publishing workflow change and independently verify relevant attestations.'),
 identity_signature_changed:event('Registry signature key identifiers changed','Registry signature key identifiers changed or disappeared. This check did not verify the signatures.','Check whether the registry rotated its signing keys and verify the package using the appropriate registry verification tools.'),
 release_attestation_lost:event('Release attestation disappeared','Previously observed release attestation material is no longer present. Presence tracking is not signature verification.','Review the release’s attestation publication and confirm the intended build identity independently.'),
 release_attestation_changed:event('Release attestation changed','Recorded attestation material changed. This does not by itself establish trusted provenance or compromise.','Compare the recorded attestation change with the intended release pipeline and verify it independently.'),
 release_attestation_mismatch:event('Release attestation metadata mismatch','Attestation metadata did not match the expected release identity. This is separate from artifact inspection.','Check the attestation subject and release identity before trusting it; regenerate incorrect evidence through the intended build pipeline.'),
 release_digest_mismatch:event('Recorded release bytes changed','The recorded release digest differs from the previously recorded bytes. A reused filename does not make the artifacts identical.','Compare the exact assets and publication history. Treat replacement bytes as a new artifact requiring inspection.'),
 delivery_mismatch:event('Delivered bytes differ','The delivery check found bytes whose digest differs from the expected artifact. This does not identify why they differ.','Check the configured target, deployed version, transformations and CDN cache. Do not overwrite the original evidence to hide a mismatch.'),
 delivery_missing:event('Delivery target unavailable','The delivery check could not obtain the expected target. This does not establish that its contents are clean.','Check the target URL, publication state and allowed access, then rerun delivery verification.'),
 delivery_redirect:event('Delivery redirected','The delivery check recorded an unexpected redirect. The destination may differ from the intended release surface.','Review the redirect chain and configured delivery target before trusting the served artifact.'),
 delivery_content_type:event('Delivery content type changed','The response media type differed from the expected type while digests matched. This is a serving-configuration fact, not a changed-bytes finding.','Correct the server or CDN Content-Type if unintended, then rerun delivery verification.'),
 fair_use_budget:event('Check allowance reached','A configured usage allowance prevented further work. A skipped check cannot establish a passing release.','Review workspace usage and the recorded limit, then retry when capacity is available.'),
};

type AlertInput={kind:string;title:string;body:string;findings?:unknown};
export function explainAlert(alert:AlertInput,operational=false){
 const findings=asFindingList(alert.findings);
 const rules=[...new Set(findings.map(f=>f.rule))].map(rule=>({rule,paths:[...new Set(findings.filter(f=>f.rule===rule).map(f=>f.path).filter(Boolean))],...((Object.hasOwn(ruleExplanations,rule)?ruleExplanations[rule]:undefined)??explain(`Finding ${rule}`,'The recorded rule has no specific explanation in this version. Use the original finding and scan scope; do not infer an unrecorded cause.','Review the rule and affected file locally before proposing a change.',rescan))}));
 if(alert.kind==='web_origin_scan')for(const rule of rules)if(rule.verify===rescan)rule.verify='Deploy the intended correction and rerun the verified website check. Review the new saved result; this only covers its recorded public assets.';
 let overview=Object.hasOwn(kindExplanations,alert.kind)?kindExplanations[alert.kind]:undefined;
 if(alert.kind==='push_sensitive_path')overview=explain('Sensitive-looking file changed','A push changed a file with a sensitive-looking name. Its contents and published release were not inspected by this check. An example file may contain only placeholders; this alert does not establish that credentials leaked.','Inspect the changed file and diff locally. Keep safe placeholders if intended. Revoke or rotate real exposed credentials; never paste secret values into chat.',rescan);
 if(!overview&&operational)overview=explain('Check incomplete','This check did not complete. It does not establish that the release passed or that content was exposed.','Review the recorded failure and source access. Attach a supported release artifact if no scannable pack was available; unsupported installers must not be relabelled to bypass the scanner.','Rerun the supported check and review its saved result. Do not resolve this as a passing scan.');
 if(!overview&&alert.kind==='map_custody_check')overview=explain('Private map custody check','This result concerns matching maps in the configured private provider and any checked public map URLs. It is separate from artifact approval.','Review the findings below, provider access and release/debug identifiers.','Rerun Map custody for the same identity and review the saved result.');
 if(!overview&&['release_scan','scan_latest_release','npm_scan','web_origin_scan'].includes(alert.kind))overview=explain(alert.kind==='web_origin_scan'?'Website asset check':alert.kind==='npm_scan'?'Published npm package check':'Release artifact check',alert.kind==='web_origin_scan'?'This result covers the public assets fetched by the recorded website check, not every page or backend.':'This result covers the recorded package bytes, not the whole repository or current deployed website.','Review each recorded rule below. Missing findings or paths are not proof that the check passed.',alert.kind==='web_origin_scan'?'Deploy the intended correction and rerun the verified website check. Review its new saved scope and result.':rescan);
 overview??=explain('Recorded event','This alert type has no specific explanation in this version. The recorded event remains the source of truth; its cause and impact have not been inferred.','Review the event details and source service. Do not assume this is a leak, compromise or passing scan.',reviewEvent);
 const pushPaths=alert.kind==='push_sensitive_path'?/^This push touched (.+?)\. NoSpoilers/.exec(alert.body)?.[1]:undefined;
 return {...overview,location:[...new Set(findings.map(f=>f.path).filter(Boolean))].join('\n')||pushPaths,steps:[overview.action,overview.verify],rules};
}
