/** Loaded only behind import.meta.env.DEV AND VITE_WEBSITE_CAPTURE_REVIEW=1. */
export type CaptureSpec = {
  id: string; destination: string; contentLocation: string; route: string;
  state: string; viewport: string; framing: string; caption: string; demonstrates: string;
};
export const CAPTURES: CaptureSpec[] = [
  { id: 'CAPTURE-WEB-PRODUCT-01', destination: '/product#inspect', contentLocation: 'site-content.ts / product / inspect', route: '/watch/releases?workspace={qaWorkspace}&upload={qaAttempt}&uploadView=detail', state: 'A saved QA sourcemap fixture with real findings, correct digest and scope.', viewport: '1440 × 1000 CSS px', framing: 'Full result header, verdict and first finding; retain enough app shell to establish context. No browser chrome.', caption: 'A saved release result keeps findings, scope and the recorded decision together.', demonstrates: 'The actual release evidence surface, not a new scan or a marketing mockup.' },
  { id: 'CAPTURE-DOCS-FIRST-SCAN-01', destination: '/docs/getting-started#scan-a-package', contentLocation: 'docs-start.ts / getting-started / scan-a-package', route: '/watch/scan?workspace={qaWorkspace}&mode=package', state: 'Signed-in QA workspace with active test entitlement, package mode before upload.', viewport: '1440 × 900 CSS px', framing: 'Launcher title, workspace context and upload controls; no fixture catalogue or developer tools.', caption: 'Choose the destination workspace before submitting the release archive.', demonstrates: 'The package entry action within the authenticated product shell.' },
  { id: 'CAPTURE-DOCS-WORKSPACE-01', destination: '/docs/workspaces-and-roles#ownership', contentLocation: 'docs-start.ts / workspaces-and-roles / ownership', route: '/watch/team?workspace={qaWorkspace}', state: 'QA-only owner, administrator, member and viewer records from approved local fixtures.', viewport: '1440 × 1000 CSS px', framing: 'Workspace name, role labels and membership list. Do not include invitation secrets.', caption: 'Workspace roles separate reading, response and administration.', demonstrates: 'Real role presentation without implying organisation billing authority or enterprise SSO.' },
  { id: 'CAPTURE-DOCS-GITHUB-01', destination: '/docs/github#connect', contentLocation: 'docs-scan.ts / github / connect', route: '/watch/sources?workspace={qaWorkspace}&configure=github', state: 'Authorised QA workspace showing the real connection entry and any current configuration limitation. No live installation changes for an image.', viewport: '1440 × 900 CSS px', framing: 'Connection heading, authority guidance and Connect action; omit any sensitive installation metadata.', caption: 'A GitHub connection requires explicit authority and installation approval.', demonstrates: 'Product workspace selection is distinct from GitHub source authorisation.' },
  { id: 'CAPTURE-DOCS-WEBSITE-01', destination: '/docs/website-scanning#ownership', contentLocation: 'docs-scan.ts / website-scanning / ownership', route: '/watch/sources?workspace={qaWorkspace}&configure=website', state: 'QA-only unverified origin, actual challenge instructions and verification actions. Use a controlled test origin, not a customer domain.', viewport: '1440 × 1000 CSS px', framing: 'Origin scope, DNS and HTTP instructions and verification buttons; redact the challenge value.', caption: 'Prove control of the exact hostname before starting a website check.', demonstrates: 'Ownership verification is a separate step, not a completed scan.' },
  { id: 'CAPTURE-DOCS-COVERAGE-01', destination: '/docs/coverage-and-releases#read-coverage', contentLocation: 'docs-review.ts / coverage-and-releases / read-coverage', route: '/watch/sources?workspace={qaWorkspace}', state: 'Approved QA sources with a saved result and a delayed or unknown cadence state; actual backend state, not DOM edits.', viewport: '1440 × 1000 CSS px', framing: 'Inventory and one selected detail showing source, scope, last check and cadence. Keep status labels legible.', caption: 'Monitoring freshness and a saved release decision answer different questions.', demonstrates: 'An older passing result does not establish current monitoring health.' },
  { id: 'CAPTURE-DOCS-RELEASE-01', destination: '/docs/release-results#open-a-result', contentLocation: 'docs-review.ts / release-results / open-a-result', route: '/watch/releases?workspace={qaWorkspace}&upload={qaAttempt}&uploadView=detail', state: 'Retained QA fixture result with exact attempt selected; real findings and private evidence.', viewport: '1440 × 1000 CSS px', framing: 'Title, outcome, scope, engine/time provenance and first finding. No customer data.', caption: 'Open a specific saved attempt to read its scope, findings and outcome.', demonstrates: 'Stable release-detail evidence, distinct from list selection or a pending upload.' },
  { id: 'CAPTURE-DOCS-ALERTS-01', destination: '/docs/alerts#queues', contentLocation: 'docs-review.ts / alerts / queues', route: '/watch/alerts?workspace={qaWorkspace}&tab=waiting&alert={qaAlert}', state: 'QA website alert acknowledged and assigned to a QA responder, with authentic retained response history.', viewport: '1440 × 1000 CSS px', framing: 'Queue labels, independent assignment, selected alert and activity. No provider send required.', caption: 'Assignment and response history are separate from the original finding evidence.', demonstrates: 'A workflow action records who responded without rewriting a scan result.' },
  { id: 'CAPTURE-DOCS-EXCEPTION-01', destination: '/docs/policies-and-exceptions#request', contentLocation: 'docs-review.ts / policies-and-exceptions / request', route: '/watch/policy?workspace={qaWorkspace}&exception={qaException}', state: 'QA-only pending saved-finding request with independent approval required and self-approval visibly unavailable.', viewport: '1440 × 1000 CSS px', framing: 'Exact rule/path/scope, reason, expiry and approval restriction. Redact unnecessary account identifiers.', caption: 'A scoped exception can require approval by a different administrator.', demonstrates: 'Pending is not approved, and risk acceptance is not remediation.' },
  { id: 'CAPTURE-DOCS-PROOF-01', destination: '/docs/proof#private-and-shared', contentLocation: 'docs-review.ts / proof / private-and-shared', route: '/watch/releases?workspace={qaWorkspace}&upload={qaAttempt}&uploadView=detail', state: 'Private QA result with sharing preview open, not published. No public link created just for a screenshot.', viewport: '1440 × 1000 CSS px', framing: 'Private sharing explanation and redacted summary preview. Exclude opaque tokens and full signed record.', caption: 'Review the redacted summary before explicitly sharing it.', demonstrates: 'Private evidence and a public summary are different projections.' },
  { id: 'CAPTURE-DOCS-TOKEN-01', destination: '/docs/api-tokens-and-ci#create-token', contentLocation: 'docs-manage.ts / api-tokens-and-ci / create-token', route: '/watch/tokens?workspace={qaWorkspace}', state: 'QA token metadata/history only, with any one-time secret reveal cleared. Never mint a customer token for an image.', viewport: '1440 × 900 CSS px', framing: 'Token name, metadata and revoke action. Remove token values, hashes and unnecessary prefixes.', caption: 'Keep scan credentials private and revoke them from workspace settings.', demonstrates: 'Metadata remains visible while token secrets are not recoverable from the list.' },
  { id: 'CAPTURE-DOCS-NOTIFICATIONS-01', destination: '/docs/notifications#configure', contentLocation: 'docs-manage.ts / notifications / configure', route: '/watch/notifications?workspace={qaWorkspace}', state: 'QA-only saved destination with truthful not-tested or provider-unavailable state; no external test message for capture.', viewport: '1440 × 1000 CSS px', framing: 'Destination type, configuration guidance and explicit test/status controls. Redact mailbox, webhook and secrets.', caption: 'Saving a destination does not establish successful delivery.', demonstrates: 'Configuration, test admission and provider acceptance are separate states.' },
];
export const CAPTURE_REDACTION = 'Use only approved local QA data. Remove customer names/domains, real emails, credentials, cookies, API tokens, verification challenges, public-share tokens and sensitive paths/findings. Never fabricate an application state or alter evidence for a capture. Obtain owner approval before adding any final image.';
export function annotateCaptures(root: HTMLElement): void {
  for (const slot of Array.from(root.querySelectorAll<HTMLElement>('[data-nsw-capture]'))) {
    const spec = CAPTURES.find(item => item.id === slot.dataset.nswCapture);
    if (!spec) continue;
    slot.className = 'nsw-review-capture';
    slot.setAttribute('role', 'note');
    slot.setAttribute('aria-label', `Image capture review: ${spec.id}`);
    slot.replaceChildren();
    const heading = document.createElement('strong');
    heading.textContent = `Review only · ${spec.id}`;
    slot.append(heading);
    for (const text of [`Route: ${spec.route}`, `State: ${spec.state}`, `Viewport: ${spec.viewport}. ${spec.framing}`, `Caption: ${spec.caption}`, `Demonstrates: ${spec.demonstrates}`, CAPTURE_REDACTION]) {
      const paragraph = document.createElement('p');
      paragraph.textContent = text;
      slot.append(paragraph);
    }
  }
}
