import {githubMark,npmMark} from './brand-marks';
/** Conceptual product illustrations, never invented customer results. */
const svg = (path:string) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
const cube = svg('<path d="m12 3 9 5v8l-9 5-9-5V8l9-5Zm0 9 9-4M12 12 3 8m9 4v9M7 5.8l10 5.5"/>');
const file = svg('<path d="M6 3h8l4 4v14H6V3Zm8 0v5h4M9 12h6M9 16h4"/>');
const shield = svg('<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>');
const code = svg('<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>');
const globe = svg('<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>');
const arrow = svg('<path d="M4 12h16m-6-6 6 6-6 6"/>');
const label = '<p class="hero-illustration-label">PRODUCT ILLUSTRATION · NOT CUSTOMER DATA</p>';

export function renderHeroVisual(path:string):string {
 if(path==='/product') return `<div class="hero-visual hero-inspect" aria-label="Illustration of inspecting a release archive"><div class="hero-window-bar"><span></span><span></span><span></span><small>Release inspection</small></div><div class="hero-artifact">${cube}<div><strong>The package that ships</strong><small>Inspect the output. Keep the context.</small></div></div><div class="hero-file-stack"><div>${file}<span>Source maps</span><small>Original source</small></div><div>${code}<span>Configuration</span><small>Private material</small></div><div>${file}<span>AI context</span><small>Prompts & instructions</small></div></div><div class="hero-inspection-foot">${shield}<span>Scope, findings and policy in one record</span></div>${label}</div>`;
 if(path==='/integrations') return `<div class="hero-visual hero-integrations" aria-label="Release surfaces connected to NoSpoilers"><div class="hero-tool-grid"><a href="/docs/github">${githubMark}<strong>GitHub</strong><small>Repositories & releases</small></a><a href="/docs/artifact-scanning">${npmMark}<strong>npm</strong><small>Published packages</small></a><a href="/docs/api-tokens-and-ci">${code}<strong>CI / CD</strong><small>Token-based submission</small></a><a href="/docs/website-scanning">${globe}<strong>Production web</strong><small>Verified origin checks</small></a></div><div class="hero-converge" aria-hidden="true"></div><div class="hero-integration-hub"><span class="hero-ns-mark">[ ]</span><strong>NoSpoilers</strong><small>One release evidence workflow</small></div><p class="hero-visual-note">Connect a surface. Keep its scope explicit.</p></div>`;
 if(path==='/use-cases') return `<div class="hero-visual hero-workflows" aria-label="Three release workflows"><a href="#packages"><span class="hero-workflow-icon">${cube}</span><div><small>BEFORE PUBLISHING</small><strong>Inspect the packed release</strong></div>${arrow}</a><a href="#websites"><span class="hero-workflow-icon">${globe}</span><div><small>AFTER DEPLOYMENT</small><strong>Watch the exposed boundary</strong></div>${arrow}</a><a href="#response"><span class="hero-workflow-icon">${shield}</span><div><small>WHEN SOMETHING CHANGES</small><strong>Investigate with evidence</strong></div>${arrow}</a><p class="hero-visual-note">Different entry points. The same evidence loop.</p></div>`;
 if(path==='/security') return `<div class="hero-visual hero-trust" aria-label="Private evidence and explicit sharing boundary"><div class="hero-trust-orbit"><div class="hero-trust-core">${shield}<strong>Private by default</strong></div><span class="hero-orbit-label">AUTHORISED SCOPE</span></div><div class="hero-trust-boundary"><span>Private evidence</span><span>Explicit sharing ${arrow}</span><span>Redacted proof</span></div><p class="hero-visual-note">A signed record authenticates a result.<br>It is not a blanket security guarantee.</p></div>`;
 if(path==='/enterprise') return `<div class="hero-visual hero-pilot"><p class="hero-pilot-kicker">YOUR EVALUATION PLAN</p><h3>Prove the fit.<br>Before you scale.</h3><ol><li><span>01</span><div><strong>Agree the scope</strong><small>Sources, roles and success criteria</small></div></li><li><span>02</span><div><strong>Run a real release</strong><small>Inspect, investigate and recheck</small></div></li><li><span>03</span><div><strong>Review the evidence</strong><small>Product fit and operating requirements</small></div></li></ol><a href="#pilot">Explore the evaluation ${arrow}</a></div>`;
 return `<div class="hero-visual hero-support"><p class="hero-pilot-kicker">HOW CAN WE HELP?</p><a href="/docs/getting-started">${cube}<div><strong>Get your first result</strong><small>Start with a small release package</small></div>${arrow}</a><a href="/docs/troubleshooting">${code}<div><strong>Unblock your workflow</strong><small>Sign-in, permissions and scan states</small></div>${arrow}</a><a href="mailto:emotiveimpact@gmail.com">${file}<div><strong>Talk to us</strong><small>Send a question—never send credentials</small></div>${arrow}</a></div>`;
}
