import {QuietSidePreview} from './design/QuietSidePreview';
import { QuietStatus } from './design/QuietComponents';
import { WatchSkeleton } from "@/components/WatchDataState";
import {useEffect,useState} from 'react';
import {Package,Globe,ArrowUpRight,X} from 'lucide-react';
import {WatchFirstProofOverview} from './WatchFirstProofOverview';
import {Button} from '@/components/ui/button';
import {navigate} from '@/nav';
import {overviewNextAction} from './overview-next-action';
import './artifact-overview.css';
import {OverviewActivity} from './OverviewActivity';
import {Dialog,DialogTitle} from '@headlessui/react';

type Overview={connectedActivity?:Array<{installationId:number;name:string;queued:number;running:number}>;workspace:{name:string;archived:boolean};counts:{total:number;active:number;attention:number;passed:number};hostedSources?:Array<{installationId:number;name:string;total:number;passed:number;attention:number}>;alertCounts?:{open:number;waiting:number;done:number;mine:number};websiteCoverage?:{total:number;attention:number;delayed:number;unverified?:number;unchecked?:number};recent:Array<{id:string;target:string;status:string;created_at:string;source_kind:'website'|'artifact';verdict:string}>};
export function ArtifactOverview({workspaceId,search,nowLabel}:{workspaceId:string;search:string;nowLabel:string}){
 return <OverviewScope key={workspaceId} workspaceId={workspaceId} search={search} nowLabel={nowLabel}/>;
}
function OverviewScope({workspaceId,search,nowLabel}:{workspaceId:string;search:string;nowLabel:string}){
 const [releaseMode,setReleaseMode]=useState<'uploads'|'connected'>('uploads');
 const [selectedId,setSelectedId]=useState<string|null>(null);
 const [data,setData]=useState<(Overview & {connectedCoverage?:{total:number;paused:number;unavailable?:number;unknown:number;delayed:number;recent:number;connections?:Array<{installationId:number;name:string}>}})|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function refresh(){try{const response=await fetch(`/api/workspaces/${encodeURIComponent(workspaceId)}/overview`,{signal:controller.signal});const body=await response.json();if(!response.ok||!body.counts||!Array.isArray(body.recent))throw new Error('Workspace overview could not be loaded.');if(controller.signal.aborted)return;setData(body);setError('');const active=body.counts.active>0||body.connectedActivity?.some((item:{queued:number;running:number})=>item.queued+item.running>0);timer=setTimeout(()=>void refresh(),active?3000:30000);}catch(err){if(!controller.signal.aborted)setError(err instanceof Error?err.message:'Workspace overview could not be loaded.');}}
  void refresh();return()=>{controller.abort();clearTimeout(timer);};
 },[workspaceId,retry]);
 function go(view:string,status?:string,id?:string){const params=new URLSearchParams();params.set('workspace',workspaceId);if(status)params.set('uploadStatus',status);if(id){params.set('upload',id);params.set('uploadView','detail');}navigate(`/watch/${view}?${params}`);}
 if(error)return <section className="overview-panel space-y-4" role="alert"><h1 className="watch-page-title">Overview unavailable</h1><p>{error} No other workspace’s evidence is shown.</p><div className="flex flex-wrap gap-3"><Button onClick={()=>{setError('');setData(null);setRetry(value=>value+1);}}>Retry</Button><Button variant="outline" onClick={()=>navigate('/watch/workspaces')}>Choose a workspace</Button></div></section>;
 if(!data)return <section aria-label="Workspace overview" aria-busy="true"><WatchSkeleton variant="list" className="mt-4" label="Loading workspace overview…" /></section>;
 const nextAction=overviewNextAction(data,workspaceId);
 const connections=data.connectedCoverage?.connections??[];
 const requestedInstall=Number(new URLSearchParams(search).get('install'));
 const connection=connections.find(item=>item.installationId===requestedInstall)??(connections.length===1?connections[0]:undefined);
 const selected=data.recent.find(row=>row.id===selectedId);
 const checked=data.connectedCoverage?.recent??0,totalSources=data.connectedCoverage?.total??0;
 const connectionLinks=data.connectedCoverage?.connections?.map(connection=><Button key={connection.installationId} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,install:String(connection.installationId)})}`)}>Review {connection.name} coverage</Button>);
 const unavailableNotice=data.connectedCoverage?.unavailable?<p role="status">{data.connectedCoverage.unavailable} sources unavailable because their connection is suspended. Review connection access in Coverage.</p>:null;
 const connectedCoverage=data.connectedCoverage?.total?<section className="overview-panel" aria-label="Connected monitoring health"><h2 className="font-display text-xl">Connected monitoring</h2><p>Repository, package, connected website and custody observations—not release safety or a worker uptime guarantee.</p><div className="mt-3 flex flex-wrap gap-2">{(['total','delayed','unknown','paused','recent','unavailable'] as const).map(state=><Button key={state} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,coverageHealth:state==='total'?'all':state})}`)}>{data.connectedCoverage![state]??0} {state==='total'?'sources':state==='recent'?'recently checked':state}</Button>)}</div><Button variant="outline" className="mt-3" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,coverageHealth:'all'})}`)}>Review connected coverage</Button>{connectionLinks?.length?<div className="mt-4"><h3 className="text-xs font-medium text-mute">Individual connections</h3><div className="mt-3 flex flex-wrap gap-2">{connectionLinks}</div></div>:null}</section>:null;
 const coverage=data.websiteCoverage?.total?<section className="overview-panel" aria-label="Website coverage health"><h2 className="font-display text-xl">Website coverage</h2><p>Connection health is separate from findings in saved scans.</p><div className="mt-3 flex flex-wrap gap-3">{([{key:'total',title:'All websites',filter:'all'},{key:'attention',title:'Need attention',filter:'attention'},{key:'delayed',title:'Monitoring delayed',filter:'delayed'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,websiteHealth:item.filter})}`)}>{item.title}: {data.websiteCoverage![item.key]}</Button>)}</div></section>:null;
 const alerts=data.alertCounts?<section className="overview-panel" aria-label="Alert response"><h2 className="font-display text-xl">Alert response</h2><p>Response status is separate from the outcome recorded in each scan.</p><div className="mt-3 flex flex-wrap gap-3">{([{key:'open',title:'Open',tab:'open'},{key:'waiting',title:'In progress',tab:'waiting'},{key:'done',title:'Resolved',tab:'done'},{key:'mine',title:'Assigned to me',tab:'mine'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/alerts?${new URLSearchParams({workspace:workspaceId,tab:item.tab})}`)}>{item.title}: {data.alertCounts![item.key]}</Button>)}</div></section>:null;
 const hasAlerts=!!data.alertCounts&&(data.alertCounts.open+data.alertCounts.waiting+data.alertCounts.done)>0;
 const hasCheckableConnectedSource=(data.connectedCoverage?.total??0)>(data.connectedCoverage?.paused??0)+(data.connectedCoverage?.unavailable??0);
 if(!data.counts.total&&!hasAlerts&&!data.hostedSources?.length&&!data.connectedActivity?.length&&!data.workspace.archived)return <><WatchFirstProofOverview search={search} nowLabel={nowLabel} connectedSources={hasCheckableConnectedSource} websiteStage={data.websiteCoverage?.total?(data.websiteCoverage.unchecked?'scan':data.websiteCoverage.unverified?'verify':'configured'):undefined}/><div className="overview-secondary mt-6">{connectedCoverage}{unavailableNotice}{coverage}</div></>;
 const latest=data.recent[0];
 const connectedSourceCount=data.connectedCoverage?.total??0;
 return <section className="uploaded-releases workspace-overview" aria-label="Workspace overview">
  <div className="uploaded-heading"><div><p className="overview-context">{data.workspace.name}</p><h1 className="watch-page-title">Your releases, at a glance.</h1><p className="watch-page-lede">{data.counts.attention||data.alertCounts?.open?'Review the evidence that needs a closer look.':'Your latest retained release evidence is ready.'} <span className="sr-only">{data.workspace.name} · Your releases and saved evidence.</span></p></div></div>
  {data.workspace.archived?<section className="overview-panel" aria-label="Archived workspace"><p role="status">Archived — history remains available. Restore the workspace before starting another scan.</p><Button variant="outline" onClick={()=>navigate('/watch/workspaces')}>Review workspace settings</Button></section>:null}
  <section className="overview-latest" aria-label="Latest release decision">
   <h2 className="sr-only">{nextAction.label}</h2>
   <div className="overview-latest-top"><p className="overview-eyebrow">{latest?'Latest release':'Next action'}</p>{latest?<QuietStatus tone={latest.verdict.startsWith('Policy passed')?'passed':latest.status==='failed'?'failed':'review'}>{latest.verdict}</QuietStatus>:null}</div>
   <h2>{latest?(latest.source_kind==='website'?'Website check':'Release artifact'):nextAction.label}{latest?<span> · {latest.target}</span>:null}</h2>
   <p>{nextAction.text}</p>
   <Button className="overview-primary" onClick={()=>latest?setSelectedId(latest.id):navigate(nextAction.href)}>{latest?'Review evidence':nextAction.label}<ArrowUpRight aria-hidden/></Button>
   <div className="overview-latest-meta"><span>{latest?new Date(latest.created_at).toLocaleString():'No saved release yet'}</span><span>{data.counts.total} saved {data.counts.total===1?'attempt':'attempts'}</span><span>{checked} of {totalSources} connected sources recently checked</span></div>
  </section>
  <div className="overview-stat-strip" aria-label="Workspace evidence totals">
   <button aria-label={`Saved attempts ${data.counts.total}`} onClick={()=>go('releases')}><strong>{data.counts.total}</strong><span>Saved scans</span></button>
   <button aria-label={`${data.counts.attention} scans requiring review`} onClick={()=>go('releases','attention')}><strong>{data.counts.attention}</strong><span>Needs review</span></button>
   <button aria-label={`${connectedSourceCount} connected sources`} onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,coverageHealth:'all'})}`)}><strong>{connectedSourceCount}</strong><span>Connected sources</span></button>
  </div>
  <section className="overview-releases" aria-label="Recent release scans"><div className="overview-section-heading"><h2>Recent release scans</h2><div className="overview-release-tabs" aria-label="Release evidence source"><button aria-pressed={releaseMode==='uploads'} onClick={()=>setReleaseMode('uploads')}>Uploaded scans</button><button aria-pressed={releaseMode==='connected'} onClick={()=>setReleaseMode('connected')}>Connected releases</button></div></div>
   {releaseMode==='uploads'?<><div className="overview-release-list">{!data.recent.length?<p className="overview-empty">No saved upload attempts yet.</p>:data.recent.slice(0,4).map(row=><article className="overview-release-row" key={row.id}><span className="overview-source-icon">{row.source_kind==='website'?<Globe aria-hidden/>:<Package aria-hidden/>}</span><div><h3>{row.source_kind==='website'?'Website check':'Artifact scan'}</h3><p>{row.target}</p></div><time dateTime={row.created_at}>{new Date(row.created_at).toLocaleString()}</time><span className={`overview-verdict ${row.verdict.startsWith('Policy passed')?'is-passed':row.status==='failed'?'is-failed':''}`}>{row.verdict}</span><button className="overview-card-action" aria-label={`View evidence for ${row.target}`} onClick={()=>setSelectedId(row.id)}>Open<ArrowUpRight aria-hidden/></button></article>)}</div><div className="overview-evidence-counts"><button className="overview-link" onClick={()=>go('releases')}>View all {data.counts.total} attempts<ArrowUpRight aria-hidden/></button><div>{([{key:'attention',label:'Need review',status:'attention'},{key:'passed',label:'Policy passed',status:'passed'},{key:'active',label:'Queued or scanning',status:'active'}] as const).map(item=><button key={item.key} onClick={()=>go('releases',item.status)} aria-label={`${item.label} ${data.counts[item.key]}`}>{item.label} <span>{data.counts[item.key]}</span></button>)}</div></div></>:<div className="overview-connected-cards">{!data.hostedSources?.length?<p className="overview-empty">No separate connected release evidence is available. Attempts linked to uploads are shown in Uploaded scans.</p>:data.hostedSources.map(source=><article className="overview-release-card" key={source.installationId}><h3>{source.name}</h3><p>{source.total} retained releases · {source.passed} policy passed · {source.attention} need review</p><button className="overview-card-action" onClick={()=>navigate(`/watch/releases?${new URLSearchParams({workspace:workspaceId,install:String(source.installationId),releaseView:'connected'})}`)}>View {source.name} releases<ArrowUpRight aria-hidden/></button></article>)}</div>}
  </section>
  <section className="overview-activity-section" aria-label="Source activity"><div className="overview-section-heading"><h2>Source activity</h2><button className="overview-link" onClick={()=>navigate(`/watch/timeline?workspace=${encodeURIComponent(workspaceId)}`)}>View timeline<ArrowUpRight aria-hidden/></button></div><OverviewActivity workspaceId={workspaceId} connection={connection}/></section>
  <section className="overview-monitoring" aria-label="Monitoring and connections"><div className="overview-secondary">
  {coverage}
  {connectedCoverage}
  {unavailableNotice}
  {alerts}
  {data.connectedActivity?.length?<section className="overview-panel" aria-label="Connected scan activity"><h2 className="font-display text-xl">Connected scan activity</h2><p>Checks are processing. Saved results will appear when evidence is published.</p><div className="mt-3 space-y-3">{data.connectedActivity.map(source=><p key={source.installationId}><strong>{source.name}</strong> · {source.queued} queued · {source.running} running</p>)}</div></section>:null}
  {data.hostedSources?.length?<section className="overview-panel" aria-label="Connected release evidence"><h2 className="font-display text-xl">Connected release evidence</h2><p>Repository and registry release records within your retention window. Attempts already listed in upload history are not counted twice.</p><div className="mt-3 space-y-3">{data.hostedSources.map(source=><div key={source.installationId} className="flex flex-wrap items-center justify-between gap-3"><strong>{source.name}</strong><div className="flex flex-wrap gap-2">{([{key:'total',label:'releases',decision:'all'},{key:'attention',label:'need review',decision:'attention'},{key:'passed',label:'policy passed',decision:'passed'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/releases?${new URLSearchParams({workspace:workspaceId,install:String(source.installationId),releaseView:'connected',hostedDecision:item.decision})}`)}>{source[item.key]} {item.label}</Button>)}</div><Button variant="outline" onClick={()=>navigate(`/watch/releases?${new URLSearchParams({workspace:workspaceId,install:String(source.installationId),releaseView:'connected'})}`)}>View {source.name} releases</Button></div>)}</div></section>:null}
  </div></section>
  <p className="overview-footnote">Saved scans are point-in-time evidence, not a guarantee of current safety. Prior attempts remain available in Releases. Alert response, scan outcomes and monitoring freshness are separate.</p>
  <Dialog open={!!selected} onClose={()=>setSelectedId(null)} className="relative z-50"><QuietSidePreview inset><div className="overview-section-heading"><span className="overview-eyebrow">Saved evidence</span><button aria-label="Close evidence preview" className="overview-drawer-close" onClick={()=>setSelectedId(null)}><X aria-hidden/></button></div><DialogTitle>{selected?.target}</DialogTitle><p>{selected?.verdict}</p><dl><div><dt>Recorded</dt><dd>{selected?new Date(selected.created_at).toLocaleString():''}</dd></div><div><dt>Source</dt><dd>{selected?.source_kind==='website'?'Website check':'Artifact scan'}</dd></div></dl><p>This is the recorded attempt summary. Open the full evidence to inspect its findings, scope and available release controls.</p><Button className="overview-primary" onClick={()=>{if(selected)go('releases',undefined,selected.id);}}>Open full evidence<ArrowUpRight aria-hidden/></Button><p>Production verification is separate from this saved scan outcome.</p></QuietSidePreview></Dialog>
 </section>;
}
