import {useEffect,useState} from 'react';
import {WatchFirstProofOverview} from './WatchFirstProofOverview';
import {Button} from '@/components/ui/button';
import {navigate} from '@/nav';
import {overviewNextAction} from './overview-next-action';

type Overview={connectedActivity?:Array<{installationId:number;name:string;queued:number;running:number}>;workspace:{name:string;archived:boolean};counts:{total:number;active:number;attention:number;passed:number};hostedSources?:Array<{installationId:number;name:string;total:number;passed:number;attention:number}>;alertCounts?:{open:number;waiting:number;done:number;mine:number};websiteCoverage?:{total:number;attention:number;delayed:number;unverified?:number;unchecked?:number};recent:Array<{id:string;target:string;status:string;created_at:string;source_kind:'website'|'artifact';verdict:string}>};
export function ArtifactOverview({workspaceId,search,nowLabel}:{workspaceId:string;search:string;nowLabel:string}){
 return <OverviewScope key={workspaceId} workspaceId={workspaceId} search={search} nowLabel={nowLabel}/>;
}
function OverviewScope({workspaceId,search,nowLabel}:{workspaceId:string;search:string;nowLabel:string}){
 const [data,setData]=useState<(Overview & {connectedCoverage?:{total:number;paused:number;unavailable?:number;unknown:number;delayed:number;recent:number;connections?:Array<{installationId:number;name:string}>}})|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function refresh(){try{const response=await fetch(`/api/workspaces/${encodeURIComponent(workspaceId)}/overview`,{signal:controller.signal});const body=await response.json();if(!response.ok||!body.counts||!Array.isArray(body.recent))throw new Error('Workspace overview could not be loaded.');if(controller.signal.aborted)return;setData(body);setError('');const active=body.counts.active>0||body.connectedActivity?.some((item:{queued:number;running:number})=>item.queued+item.running>0);timer=setTimeout(()=>void refresh(),active?3000:30000);}catch(err){if(!controller.signal.aborted)setError(err instanceof Error?err.message:'Workspace overview could not be loaded.');}}
  void refresh();return()=>{controller.abort();clearTimeout(timer);};
 },[workspaceId,retry]);
 function go(view:string,status?:string,id?:string){const params=new URLSearchParams();params.set('workspace',workspaceId);if(status)params.set('uploadStatus',status);if(id){params.set('upload',id);params.set('uploadView','detail');}navigate(`/watch/${view}?${params}`);}
 if(error)return <section className="watch-empty" role="alert"><h1 className="watch-page-title">Overview unavailable</h1><p>{error} No other workspace’s evidence is shown.</p><Button onClick={()=>{setError('');setData(null);setRetry(value=>value+1);}}>Retry</Button></section>;
 if(!data)return <p role="status">Loading your workspace overview…</p>;
 const nextAction=overviewNextAction(data,workspaceId);
 const connectionLinks=data.connectedCoverage?.connections?.map(connection=><Button key={connection.installationId} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,install:String(connection.installationId)})}`)}>Review {connection.name} coverage</Button>);
 const unavailableNotice=!!data.connectedCoverage?.unavailable?<p role="status">{data.connectedCoverage.unavailable} sources unavailable because their connection is suspended. Review connection access in Coverage.</p>:null;
 const connectedCoverage=data.connectedCoverage?.total?<section className="watch-empty my-6" aria-label="Connected monitoring health"><h2 className="font-display text-xl">Connected monitoring</h2><p>Repository, package, connected website and custody observations—not release safety or a worker uptime guarantee.</p><div className="mt-3 flex flex-wrap gap-2">{(['total','delayed','unknown','paused','recent','unavailable'] as const).map(state=><Button key={state} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,coverageHealth:state==='total'?'all':state})}`)}>{data.connectedCoverage![state]??0} {state==='total'?'sources':state==='recent'?'recently checked':state}</Button>)}</div><Button variant="outline" className="mt-3" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,coverageHealth:'all'})}`)}>Review connected coverage</Button></section>:null;
 const coverage=data.websiteCoverage?.total?<section className="watch-empty my-6" aria-label="Website coverage health"><h2 className="font-display text-xl">Website coverage</h2><p>Connection health is separate from findings in saved scans.</p><div className="mt-3 flex flex-wrap gap-3">{([{key:'total',title:'All websites',filter:'all'},{key:'attention',title:'Need attention',filter:'attention'},{key:'delayed',title:'Monitoring delayed',filter:'delayed'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,websiteHealth:item.filter})}`)}>{item.title}: {data.websiteCoverage![item.key]}</Button>)}</div></section>:null;
 const alerts=data.alertCounts?<section className="watch-empty my-6" aria-label="Exposure response"><h2 className="font-display text-xl">Exposure response</h2><p>Response status is separate from the outcome recorded in each scan.</p><div className="mt-3 flex flex-wrap gap-3">{([{key:'open',title:'Open',tab:'open'},{key:'waiting',title:'In progress',tab:'waiting'},{key:'done',title:'Resolved',tab:'done'},{key:'mine',title:'Assigned to me',tab:'mine'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/alerts?${new URLSearchParams({workspace:workspaceId,tab:item.tab})}`)}>{item.title}: {data.alertCounts![item.key]}</Button>)}</div></section>:null;
 const hasAlerts=!!data.alertCounts&&(data.alertCounts.open+data.alertCounts.waiting+data.alertCounts.done)>0;
 const hasCheckableConnectedSource=(data.connectedCoverage?.total??0)>(data.connectedCoverage?.paused??0)+(data.connectedCoverage?.unavailable??0);
 if(!data.counts.total&&!hasAlerts&&!data.hostedSources?.length&&!data.connectedActivity?.length&&!data.workspace.archived)return <>{connectedCoverage}<div className="flex flex-wrap gap-2">{connectionLinks}</div>{unavailableNotice}{coverage}<WatchFirstProofOverview search={search} nowLabel={nowLabel} connectedSources={hasCheckableConnectedSource} websiteStage={data.websiteCoverage?.total?(data.websiteCoverage.unchecked?'scan':data.websiteCoverage.unverified?'verify':'configured'):undefined}/></>;
 return <section className="uploaded-releases" aria-label="Workspace overview">
  <div className="uploaded-heading"><div><p className="watch-kicker">{nowLabel}</p><h1 className="watch-page-title">{data.workspace.name}</h1><p className="watch-page-lede">Saved scan evidence and what needs your attention.</p></div><Button disabled={data.workspace.archived} onClick={()=>go('scan')}>New scan</Button></div>
  {data.workspace.archived?<p role="status">Archived — history remains available. Restore the workspace before starting another scan.</p>:null}
  {coverage}
  {connectedCoverage}
  <div className="flex flex-wrap gap-2">{connectionLinks}</div>
  {unavailableNotice}
  {alerts}
  {data.connectedActivity?.length?<section className="watch-empty my-6" aria-label="Connected scan activity"><h2 className="font-display text-xl">Connected scan activity</h2><p>Checks are processing. Saved results will appear when evidence is published.</p><div className="mt-3 space-y-3">{data.connectedActivity.map(source=><p key={source.installationId}><strong>{source.name}</strong> · {source.queued} queued · {source.running} running</p>)}</div></section>:null}
  {data.hostedSources?.length?<section className="watch-empty my-6" aria-label="Connected release evidence"><h2 className="font-display text-xl">Connected release evidence</h2><p>Repository and registry release records within your retention window. Attempts already listed in upload history are not counted twice.</p><div className="mt-3 space-y-3">{data.hostedSources.map(source=><div key={source.installationId} className="flex flex-wrap items-center justify-between gap-3"><strong>{source.name}</strong><div className="flex flex-wrap gap-2">{([{key:'total',label:'releases',decision:'all'},{key:'attention',label:'need review',decision:'attention'},{key:'passed',label:'policy passed',decision:'passed'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/releases?${new URLSearchParams({workspace:workspaceId,install:String(source.installationId),hostedDecision:item.decision})}`)}>{source[item.key]} {item.label}</Button>)}</div><Button variant="outline" onClick={()=>navigate(`/watch/releases?${new URLSearchParams({workspace:workspaceId,install:String(source.installationId)})}`)}>View {source.name} releases</Button></div>)}</div></section>:null}
  <div className="grid gap-4 sm:grid-cols-3 my-6" aria-label="All-time saved scan totals">
   {([{key:'attention',title:'Need review',status:'attention'},{key:'active',title:'Queued or scanning',status:'active'},{key:'passed',title:'Policy passed',status:'passed'}] as const).map(card=><button className="watch-empty text-left" key={card.key} onClick={()=>go('releases',card.status)}><span>{card.title}</span><strong className="block font-display text-3xl mt-2">{data.counts[card.key]}</strong></button>)}
  </div>
  <section className="watch-empty"><h2 className="font-display text-xl">Next action</h2><p>{nextAction.text}</p><Button variant="outline" className="mt-4" onClick={()=>navigate(nextAction.href)}>{nextAction.label}</Button></section>
  <section className="mt-6"><div className="uploaded-heading"><h2 className="font-display text-xl">Recent attempts</h2><Button variant="ghost" onClick={()=>go('releases')}>{data.counts.total===1?'View release history':`View all ${data.counts.total} attempts`}</Button></div><div className="uploaded-list">{data.recent.map(row=><button key={row.id} onClick={()=>go('releases',undefined,row.id)}><strong>{row.target}</strong><span>{row.verdict}</span><small>{row.source_kind==='website'?'Website check':'Artifact scan'} · {new Date(row.created_at).toLocaleString()}</small></button>)}</div></section>
  <p className="text-mute mt-6">Saved scans are point-in-time evidence, not a guarantee of current safety. Review connected sources in Coverage; these totals do not represent ongoing monitoring health.</p>
 </section>;
}
