import { WatchSkeleton } from "@/components/WatchDataState";
import {useEffect,useState} from 'react';
import {CircleAlert,PackageSearch,Package,Globe,ArrowUpRight,X} from 'lucide-react';
import {WatchFirstProofOverview} from './WatchFirstProofOverview';
import {Button} from '@/components/ui/button';
import {navigate} from '@/nav';
import {overviewNextAction} from './overview-next-action';
import './artifact-overview.css';
import {OverviewActivity,OverviewAttention} from './OverviewActivity';
import {Dialog,DialogBackdrop,DialogPanel,DialogTitle} from '@headlessui/react';

type Overview={connectedActivity?:Array<{installationId:number;name:string;queued:number;running:number}>;workspace:{name:string;archived:boolean};counts:{total:number;active:number;attention:number;passed:number};hostedSources?:Array<{installationId:number;name:string;total:number;passed:number;attention:number}>;alertCounts?:{open:number;waiting:number;done:number;mine:number};websiteCoverage?:{total:number;attention:number;delayed:number;unverified?:number;unchecked?:number};recent:Array<{id:string;target:string;status:string;created_at:string;source_kind:'website'|'artifact';verdict:string}>};
export function ArtifactOverview({workspaceId,search,nowLabel}:{workspaceId:string;search:string;nowLabel:string}){
 return <OverviewScope key={workspaceId} workspaceId={workspaceId} search={search} nowLabel={nowLabel}/>;
}
function OverviewScope({workspaceId,search,nowLabel}:{workspaceId:string;search:string;nowLabel:string}){
 const [releaseMode,setReleaseMode]=useState<'uploads'|'connected'>('uploads');
 const [selectedId,setSelectedId]=useState<string|null>(null);
 const [data,setData]=useState<(Overview & {connectedCoverage?:{total:number;paused:number;unavailable?:number;unknown:number;delayed:number;recent:number;connections?:Array<{installationId:number;name:string}>}})|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function refresh(){try{const response=await fetch(`/api/workspaces/${encodeURIComponent(workspaceId)}/overview`,{signal:controller.signal});const body=await response.json();if(!response.ok||!body.counts||!Array.isArray(body.recent))throw new Error('Workspace overview could not be loaded.');if(controller.signal.aborted)return;setData(body);setError('');const active=body.counts.active>0||body.connectedActivity?.some((item:{queued:number;running:number})=>item.queued+item.running>0);timer=setTimeout(()=>void refresh(),active?3000:30000);}catch(err){if(!controller.signal.aborted)setError(err instanceof Error?err.message:'Workspace overview could not be loaded.');}}
  void refresh();return()=>{controller.abort();clearTimeout(timer);};
 },[workspaceId,retry]);
 function go(view:string,status?:string,id?:string){const params=new URLSearchParams();params.set('workspace',workspaceId);if(status)params.set('uploadStatus',status);if(id){params.set('upload',id);params.set('uploadView','detail');}navigate(`/watch/${view}?${params}`);}
 if(error)return <section className="overview-panel space-y-4" role="alert"><h1 className="watch-page-title">Overview unavailable</h1><p>{error} No other workspace’s evidence is shown.</p><div className="flex flex-wrap gap-3"><Button onClick={()=>{setError('');setData(null);setRetry(value=>value+1);}}>Retry</Button><Button variant="outline" onClick={()=>navigate('/watch/workspaces')}>Choose a workspace</Button></div></section>;
 if(!data)return <section aria-label="Workspace overview" aria-busy="true"><h1 className="watch-page-title">Overview</h1><p className="watch-page-lede">Reading this workspace’s saved evidence.</p><WatchSkeleton variant="list" className="mt-4" label="Loading workspace overview…" /></section>;
 const nextAction=overviewNextAction(data,workspaceId);
 const connections=data.connectedCoverage?.connections??[];
 const requestedInstall=Number(new URLSearchParams(search).get('install'));
 const connection=connections.find(item=>item.installationId===requestedInstall)??(connections.length===1?connections[0]:undefined);
 const selected=data.recent.find(row=>row.id===selectedId);
 const activityTotal=data.counts.active+(data.connectedActivity??[]).reduce((sum,item)=>sum+item.queued+item.running,0);
 const checked=data.connectedCoverage?.recent??0,totalSources=data.connectedCoverage?.total??0;
 const connectionLinks=data.connectedCoverage?.connections?.map(connection=><Button key={connection.installationId} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,install:String(connection.installationId)})}`)}>Review {connection.name} coverage</Button>);
 const unavailableNotice=data.connectedCoverage?.unavailable?<p role="status">{data.connectedCoverage.unavailable} sources unavailable because their connection is suspended. Review connection access in Coverage.</p>:null;
 const connectedCoverage=data.connectedCoverage?.total?<section className="overview-panel" aria-label="Connected monitoring health"><h2 className="font-display text-xl">Connected monitoring</h2><p>Repository, package, connected website and custody observations—not release safety or a worker uptime guarantee.</p><div className="mt-3 flex flex-wrap gap-2">{(['total','delayed','unknown','paused','recent','unavailable'] as const).map(state=><Button key={state} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,coverageHealth:state==='total'?'all':state})}`)}>{data.connectedCoverage![state]??0} {state==='total'?'sources':state==='recent'?'recently checked':state}</Button>)}</div><Button variant="outline" className="mt-3" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,coverageHealth:'all'})}`)}>Review connected coverage</Button>{connectionLinks?.length?<details className="mt-4"><summary>Individual connections</summary><div className="mt-3 flex flex-wrap gap-2">{connectionLinks}</div></details>:null}</section>:null;
 const coverage=data.websiteCoverage?.total?<section className="overview-panel" aria-label="Website coverage health"><h2 className="font-display text-xl">Website coverage</h2><p>Connection health is separate from findings in saved scans.</p><div className="mt-3 flex flex-wrap gap-3">{([{key:'total',title:'All websites',filter:'all'},{key:'attention',title:'Need attention',filter:'attention'},{key:'delayed',title:'Monitoring delayed',filter:'delayed'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,websiteHealth:item.filter})}`)}>{item.title}: {data.websiteCoverage![item.key]}</Button>)}</div></section>:null;
 const alerts=data.alertCounts?<section className="overview-panel" aria-label="Alert response"><h2 className="font-display text-xl">Alert response</h2><p>Response status is separate from the outcome recorded in each scan.</p><div className="mt-3 flex flex-wrap gap-3">{([{key:'open',title:'Open',tab:'open'},{key:'waiting',title:'In progress',tab:'waiting'},{key:'done',title:'Resolved',tab:'done'},{key:'mine',title:'Assigned to me',tab:'mine'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/alerts?${new URLSearchParams({workspace:workspaceId,tab:item.tab})}`)}>{item.title}: {data.alertCounts![item.key]}</Button>)}</div></section>:null;
 const hasAlerts=!!data.alertCounts&&(data.alertCounts.open+data.alertCounts.waiting+data.alertCounts.done)>0;
 const hasCheckableConnectedSource=(data.connectedCoverage?.total??0)>(data.connectedCoverage?.paused??0)+(data.connectedCoverage?.unavailable??0);
 if(!data.counts.total&&!hasAlerts&&!data.hostedSources?.length&&!data.connectedActivity?.length&&!data.workspace.archived)return <><WatchFirstProofOverview search={search} nowLabel={nowLabel} connectedSources={hasCheckableConnectedSource} websiteStage={data.websiteCoverage?.total?(data.websiteCoverage.unchecked?'scan':data.websiteCoverage.unverified?'verify':'configured'):undefined}/><div className="overview-secondary mt-6">{connectedCoverage}{unavailableNotice}{coverage}</div></>;
 return <section className="uploaded-releases workspace-overview" aria-label="Workspace overview">
  <div className="uploaded-heading"><div><p className="overview-context">{data.workspace.name} · Workspace overview</p><h1 className="watch-page-title">A clearer view of every release.</h1><p className="watch-page-lede">{data.workspace.name} · Your releases, and what needs a closer look.</p></div></div>
  {data.workspace.archived?<section className="overview-panel" aria-label="Archived workspace"><p role="status">Archived — history remains available. Restore the workspace before starting another scan.</p><Button variant="outline" onClick={()=>navigate('/watch/workspaces')}>Review workspace settings</Button></section>:null}
  <div className="overview-hero">
   <div className="overview-hero-left">
    <section className="overview-next"><p className="overview-eyebrow">Next action · Release evidence</p><h2>{nextAction.label}</h2><p>{nextAction.text}</p><Button className="overview-primary" onClick={()=>navigate(nextAction.href)}>{nextAction.label}<ArrowUpRight aria-hidden/></Button><small>An incomplete check is not a detected leak.</small></section>
    <div className="overview-metrics">
     <button className="overview-metric" aria-label={`Saved attempts ${data.counts.total}`} onClick={()=>go('releases')}><strong>{data.counts.total}</strong><PackageSearch aria-hidden/><span>Saved attempts</span><small>{data.counts.passed} policy passed · {data.counts.attention} need review</small></button>
     <button className="overview-metric overview-metric-attention" aria-label={`Open checks ${data.alertCounts?.open??0}`} onClick={()=>navigate(`/watch/alerts?${new URLSearchParams({workspace:workspaceId,tab:'open'})}`)}><strong>{data.alertCounts?.open??0}</strong><CircleAlert aria-hidden/><span>Open checks</span><small>Workspace alerts requiring a response</small></button>
    </div>
   </div>
   <aside className="overview-panel overview-coverage" aria-label="Connected coverage summary"><p className="overview-eyebrow">Connected coverage</p><div className="overview-coverage-total">{totalSources}<span>sources</span></div><dl><div><dt>Recently checked</dt><dd>{checked}</dd></div><div><dt>Unknown or delayed</dt><dd>{(data.connectedCoverage?.unknown??0)+(data.connectedCoverage?.delayed??0)}</dd></div><div><dt>Paused or unavailable</dt><dd>{(data.connectedCoverage?.paused??0)+(data.connectedCoverage?.unavailable??0)}</dd></div><div><dt>Queued or scanning</dt><dd>{activityTotal}</dd></div></dl><div className="overview-coverage-progress"><span className="overview-coverage-ring" aria-hidden style={{background:`conic-gradient(#d99a2b ${totalSources?Math.min(100,checked/totalSources*100):0}%,#ffffff0b 0)`}}><span>{totalSources?Math.round(checked/totalSources*100):0}%</span></span><div><strong>{checked} of {totalSources} recently checked</strong><p>Monitoring freshness.<br/>Separate from release safety.</p></div></div><button className="overview-link" onClick={()=>navigate(`/watch/sources?${new URLSearchParams({workspace:workspaceId,coverageHealth:'all'})}`)}>Review connections<ArrowUpRight aria-hidden/></button></aside>
  </div>
  <div className="overview-dashboard-grid"><OverviewActivity workspaceId={workspaceId} connection={connection}/>{data.alertCounts?<OverviewAttention workspaceId={workspaceId} counts={data.alertCounts}/>:<section className="overview-panel"><h2>Needs attention</h2><p>Open Alerts to review workspace responses.</p><button className="overview-link" onClick={()=>navigate(`/watch/alerts?workspace=${encodeURIComponent(workspaceId)}`)}>View alerts<ArrowUpRight aria-hidden/></button></section>}</div>
  <section className="overview-releases" aria-label="Recent release scans"><div className="overview-section-heading"><h2>Recent release scans</h2><div className="overview-release-tabs" aria-label="Release evidence source"><button aria-pressed={releaseMode==='uploads'} onClick={()=>setReleaseMode('uploads')}>Uploaded scans</button><button aria-pressed={releaseMode==='connected'} onClick={()=>setReleaseMode('connected')}>Connected releases</button></div></div>
   {releaseMode==='uploads'?<><div className="overview-release-deck">{!data.recent.length?<p className="overview-empty">No saved upload attempts yet.</p>:data.recent.slice(0,3).map(row=><article className="overview-release-card" key={row.id}><div className="overview-release-card-top"><span className="overview-source-icon">{row.source_kind==='website'?<Globe aria-hidden/>:<Package aria-hidden/>}</span><span className={`overview-verdict ${row.verdict.startsWith('Policy passed')?'is-passed':row.status==='failed'?'is-failed':''}`}>{row.verdict}</span></div><h3>{row.source_kind==='website'?'Website check':'Artifact scan'}</h3><p className="overview-artifact-name">{row.target}</p><dl><div><dt>Recorded</dt><dd>{new Date(row.created_at).toLocaleString()}</dd></div><div><dt>Evidence</dt><dd>{row.status==='failed'?'Failed attempt':row.status==='queued'||row.status==='running'?'Still processing':'Saved scan result'}</dd></div></dl><button className="overview-card-action" aria-label={`View evidence for ${row.target}`} onClick={()=>setSelectedId(row.id)}>View evidence<ArrowUpRight aria-hidden/></button></article>)}</div><div className="overview-evidence-counts"><button className="overview-link" onClick={()=>go('releases')}>View all {data.counts.total} attempts<ArrowUpRight aria-hidden/></button><div>{([{key:'attention',label:'Need review',status:'attention'},{key:'passed',label:'Policy passed',status:'passed'},{key:'active',label:'Queued or scanning',status:'active'}] as const).map(item=><button key={item.key} onClick={()=>go('releases',item.status)} aria-label={`${item.label} ${data.counts[item.key]}`}>{item.label} <span>{data.counts[item.key]}</span></button>)}</div></div></>:<div className="overview-connected-cards">{!data.hostedSources?.length?<p className="overview-empty">No separate connected release evidence is available. Attempts linked to uploads are shown in Uploaded scans.</p>:data.hostedSources.map(source=><article className="overview-release-card" key={source.installationId}><h3>{source.name}</h3><p>{source.total} retained releases · {source.passed} policy passed · {source.attention} need review</p><button className="overview-card-action" onClick={()=>navigate(`/watch/releases?${new URLSearchParams({workspace:workspaceId,install:String(source.installationId),releaseView:'connected'})}`)}>View {source.name} releases<ArrowUpRight aria-hidden/></button></article>)}</div>}
  </section>
  <details className="overview-monitoring"><summary>Monitoring &amp; connections</summary><div className="overview-secondary">
  {coverage}
  {connectedCoverage}
  {unavailableNotice}
  {alerts}
  {data.connectedActivity?.length?<section className="overview-panel" aria-label="Connected scan activity"><h2 className="font-display text-xl">Connected scan activity</h2><p>Checks are processing. Saved results will appear when evidence is published.</p><div className="mt-3 space-y-3">{data.connectedActivity.map(source=><p key={source.installationId}><strong>{source.name}</strong> · {source.queued} queued · {source.running} running</p>)}</div></section>:null}
  {data.hostedSources?.length?<section className="overview-panel" aria-label="Connected release evidence"><h2 className="font-display text-xl">Connected release evidence</h2><p>Repository and registry release records within your retention window. Attempts already listed in upload history are not counted twice.</p><div className="mt-3 space-y-3">{data.hostedSources.map(source=><div key={source.installationId} className="flex flex-wrap items-center justify-between gap-3"><strong>{source.name}</strong><div className="flex flex-wrap gap-2">{([{key:'total',label:'releases',decision:'all'},{key:'attention',label:'need review',decision:'attention'},{key:'passed',label:'policy passed',decision:'passed'}] as const).map(item=><Button key={item.key} variant="outline" onClick={()=>navigate(`/watch/releases?${new URLSearchParams({workspace:workspaceId,install:String(source.installationId),releaseView:'connected',hostedDecision:item.decision})}`)}>{source[item.key]} {item.label}</Button>)}</div><Button variant="outline" onClick={()=>navigate(`/watch/releases?${new URLSearchParams({workspace:workspaceId,install:String(source.installationId),releaseView:'connected'})}`)}>View {source.name} releases</Button></div>)}</div></section>:null}
  </div></details>
  <p className="overview-footnote">Saved scans are point-in-time evidence, not a guarantee of current safety. Alert response, scan outcomes and monitoring freshness are separate.</p>
  <Dialog open={!!selected} onClose={()=>setSelectedId(null)} className="relative z-50"><DialogBackdrop className="fixed inset-0 bg-black/60 backdrop-blur-sm"/><div className="fixed inset-0 flex justify-end p-3"><DialogPanel className="overview-evidence-drawer"><div className="overview-section-heading"><span className="overview-eyebrow">Saved evidence</span><button aria-label="Close evidence preview" className="overview-drawer-close" onClick={()=>setSelectedId(null)}><X aria-hidden/></button></div><DialogTitle>{selected?.target}</DialogTitle><p>{selected?.verdict}</p><dl><div><dt>Recorded</dt><dd>{selected?new Date(selected.created_at).toLocaleString():''}</dd></div><div><dt>Source</dt><dd>{selected?.source_kind==='website'?'Website check':'Artifact scan'}</dd></div></dl><p>This is the recorded attempt summary. Open the full evidence to inspect its findings, scope and available release controls.</p><Button className="overview-primary" onClick={()=>{if(selected)go('releases',undefined,selected.id);}}>Open full evidence<ArrowUpRight aria-hidden/></Button><p>Production verification is separate from this saved scan outcome.</p></DialogPanel></div></Dialog>
 </section>;
}
