import './release-responsive.css';
import './connected-release-workspace.css';
import './design/release-workspace.css';
import {Dialog,DialogBackdrop,DialogPanel,DialogTitle} from '@headlessui/react';
import { WatchSkeleton } from '@/components/WatchDataState';
import {useEffect,useState,type ReactNode} from 'react';
import {ArrowRight,X} from 'lucide-react';
import type {ScanReport} from '@/scanner/types';
import {Button} from '@/components/ui/button';
import {navigate} from '@/nav';
import {findingCategory,type EvidenceCategory} from '@/watch/uploaded-release';
import {WorkspaceExceptionRequest} from './WorkspaceExceptionRequest';
import {ReleaseAssurancePanel} from './ReleaseAssurancePanel';
type Evidence={available:true;workspaceId:string|null;report:ScanReport}|{available:false;reason:string};
export function HostedReleaseEvidence(props:{releaseId:number;receiptId:number;search:string;activeSection?:string;decisionControls?:ReactNode;onReport?:(report:ScanReport|null)=>void;onReviewFix?:()=>void;onReveal?:(section:'findings'|'proof'|'controls')=>void;onAssessment?:(assessment:import('@/assurance/types').Assessment|null)=>void}){
 return <><div hidden={props.activeSection!=null&&!['findings','files'].includes(props.activeSection)}><ScopedEvidence key={props.releaseId} {...props}/></div><section hidden={props.activeSection!=null&&props.activeSection!=='history'} className="journey-hosted-tools"><h2 className="sr-only">History & verify a fix</h2><ReleaseAssurancePanel kind="release" recordId={props.releaseId} evidenceId={`assurance-findings-${props.releaseId}`} onReveal={props.onReveal} onAssessment={props.onAssessment} decisionControls={props.decisionControls}/></section></>;
}
function RecordedExceptions({report}:{report:ScanReport}){
 return <section className="connected-recorded-exceptions" aria-label="Recorded policy exceptions"><h3>Recorded policy exceptions <span>{report.suppressed?.length??0}</span></h3>{report.suppressed?.length?report.suppressed.map((entry,i)=><article key={i}><strong>{entry.finding.rule}</strong><code>{entry.finding.path}</code><p>{entry.reason}</p><p>Recorded by {entry.actor} · expires {entry.expiresAt}</p></article>):<p>No exceptions were applied to this scan. A later exception does not rewrite this record.</p>}</section>;
}
function ScopedEvidence({releaseId,receiptId,search,activeSection,onReveal,onReport,onReviewFix}:{releaseId:number;receiptId:number;search:string;activeSection?:string;onReport?:(report:ScanReport|null)=>void;onReviewFix?:()=>void;onReveal?:(section:'findings'|'proof'|'controls')=>void}){
 const [data,setData]=useState<Evidence|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[category,setCategory]=useState<EvidenceCategory>('all'),[inspectedPath,setInspectedPath]=useState<string|null>(null);
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');onReport?.(null);void fetch(`/api/releases/${releaseId}/evidence`,{signal:controller.signal}).then(async r=>{
  const body=await r.json();if(!r.ok)throw new Error(body.error??'Release evidence unavailable.');
  if(typeof body.available!=='boolean'||body.available&&!Array.isArray(body.report?.findings))throw new Error('Release evidence response was incomplete.');
  if(!controller.signal.aborted){setData(body);onReport?.(body.available?body.report:null);}
 }).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Release evidence unavailable.');});return()=>controller.abort();},[releaseId,retry,onReport]);
 const value=new URLSearchParams(search).get('releaseFinding');
 const index=value===null?0:/^\d+$/.test(value)?Number(value):-1;
 const findings=data?.available?data.report.findings:[];
 const categories: [EvidenceCategory,string][]=[['maps','Maps'],['secrets','Secrets'],['files','Files'],['ai','AI context']];
 const populated=categories.filter(([key])=>findings.some(finding=>findingCategory(finding)===key));
 const effectiveCategory=populated.length>1?category:'all';
 const visible=findings.map((finding,index)=>({finding,index})).filter(({finding})=>effectiveCategory==='all'||findingCategory(finding)===effectiveCategory);
 const selected=visible.find(row=>row.index===index)?.finding??null;
 function choose(index:number){const params=new URLSearchParams(search);params.set('releaseFinding',String(index));navigate(`${window.location.pathname}?${params}`);}
 function filter(next:EvidenceCategory){setCategory(next);if(next!=='all'&&findings[index]&&findingCategory(findings[index])!==next){const first=findings.findIndex(finding=>findingCategory(finding)===next);if(first>=0)choose(first);}}
 const inspectedFile=data?.available?data.report.manifest?.find(file=>file.path===inspectedPath):undefined;
 const loading=error?<div role="alert"><p>{error}</p><Button variant="outline" onClick={()=>setRetry(n=>n+1)}>Retry evidence</Button></div>:!data?<WatchSkeleton variant="list"/>:!data.available?<p>{data.reason}</p>:null;
 if(activeSection==='files')return <section aria-label="Inspected release files" className="journey-hosted-files"><div className="connected-section-heading"><h2>Artifact identity & files</h2><p>Exact bytes and checks retained with this release.</p></div>{loading??(data?.available?<><dl className="connected-artifact-facts"><div><dt>Format</dt><dd>{data.report.kind??'Not recorded'}</dd></div><div><dt>Archive size</dt><dd>{data.report.artifactBytes!=null?`${data.report.artifactBytes.toLocaleString()} bytes`:'Not recorded'}</dd></div><div><dt>Inspected files</dt><dd>{data.report.fileCount??'Not recorded'}</dd></div><div className="connected-full-fact"><dt>Artifact SHA-256</dt><dd><code>{data.report.artifactSha256??'Not retained with this report'}</code></dd></div></dl>{data.report.manifest?.length?<><div className="journey-release-table-wrap"><table className="journey-release-table"><thead><tr><th scope="col">File</th><th scope="col">Size</th><th scope="col">SHA-256</th><th scope="col"><span className="sr-only">File details</span></th></tr></thead><tbody>{data.report.manifest.map(file=><tr key={file.path}><td><code>{file.path}</code></td><td>{file.size.toLocaleString()} bytes</td><td><code>{file.sha256}</code></td><td><button type="button" className="connected-inspect-file" onClick={()=>setInspectedPath(file.path)} aria-label={`Inspect ${file.path}`}>Inspect <ArrowRight className="size-3" aria-hidden/></button></td></tr>)}</tbody></table></div><p className="journey-release-scope">{data.report.fileCount} files inspected. This is the retained artifact manifest.</p></>:<p>No file manifest was retained with this release. Findings alone do not establish a complete file inventory.</p>}<RecordedExceptions report={data.report}/><Dialog open={Boolean(inspectedFile)} onClose={()=>setInspectedPath(null)} className="release-workspace-dialog"><DialogBackdrop className="release-workspace-backdrop"/><div className="release-workspace-dialog-position"><DialogPanel className="release-workspace-dialog-panel"><div className="release-workspace-dialog-heading"><DialogTitle>Recorded file metadata</DialogTitle><button type="button" onClick={()=>setInspectedPath(null)} aria-label="Close file details"><X aria-hidden/></button></div><dl className="connected-file-metadata"><div><dt>Path</dt><dd><code>{inspectedFile?.path}</code></dd></div><div><dt>Size</dt><dd>{inspectedFile?.size.toLocaleString()} bytes</dd></div><div><dt>SHA-256</dt><dd><code>{inspectedFile?.sha256}</code></dd></div></dl><p>This is retained metadata for the inspected file, not a download of its contents.</p><Button variant="outline" onClick={()=>setInspectedPath(null)}>Close</Button></DialogPanel></div></Dialog></>:null)}</section>;
 return <section id={`assurance-findings-${releaseId}`} className="hosted-release-evidence" aria-label="Saved release findings"><h2 className="sr-only">Recorded findings</h2>
  {loading??(data?.available?<>
   {populated.length>1?<div className="connected-finding-filters" role="group" aria-label="Finding category">{([['all','All findings'],...populated] as [EvidenceCategory,string][]).map(([key,label])=><button type="button" key={key} aria-pressed={effectiveCategory===key} onClick={()=>filter(key)}>{label} <span>{key==='all'?findings.length:findings.filter(f=>findingCategory(f)===key).length}</span></button>)}</div>:null}
   {findings.length?<div className="upload-evidence-grid"><div className="upload-finding-list" aria-label="Recorded findings">{visible.map(({finding,index:i})=><button type="button" key={i} aria-pressed={index===i} onClick={()=>choose(i)}><span><strong>{finding.title}</strong><code>{finding.path}</code></span><ArrowRight className="size-4" aria-hidden/></button>)}</div><aside className="upload-evidence-panel" aria-live="polite" aria-label="Selected recorded finding">{selected?<><span className={`upload-severity is-${selected.severity}`}>{selected.severity==='critical'?'Critical':'Warning'} · {categories.find(([key])=>key===findingCategory(selected))?.[1]}</span><h3>{selected.title}</h3><div className="journey-affected-label">Affected file</div><code className="break-all">{selected.path}</code><div className="journey-finding-explanation"><section><h4>Why it matters</h4><p>{selected.detail}</p></section><section><h4>What to change</h4><p>Review the affected file in the release build and address or explicitly assess the exposure. Scan a rebuilt artifact to check the finding again.</p></section></div><div className="connected-finding-actions">{onReveal?<Button onClick={()=>onReviewFix?onReviewFix():onReveal('controls')}>Review a fix <ArrowRight className="size-4" aria-hidden/></Button>:null}{data.workspaceId?<WorkspaceExceptionRequest workspaceId={data.workspaceId} receiptId={receiptId} findingIndex={index} website={false}/>:<p>Workspace ownership is unavailable for this historical record.</p>}</div><p className="journey-release-scope">Original evidence stays unchanged. An exception request does not approve the release.</p></>:<p>Select a recorded finding. The linked finding is unavailable.</p>}</aside></div>:<p>No unsuppressed findings were recorded. This alone does not establish complete coverage.</p>}
   {activeSection==null?<RecordedExceptions report={data.report}/>:null}
  </>:null)}
 </section>;
}
