import { WatchSkeleton } from "@/components/WatchDataState";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {OrganizationBilling} from './OrganizationBilling';
import {WorkspaceDeletionRequest} from './WorkspaceDeletionRequest';
import {SettingsTabs} from './design/SettingsTabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/motion/select';
import './workspace-settings.css';
export type ManagedOrganization={id:string;name:string;role:string;workspace_limit:number;billing_available?:boolean};
type Access={organization:ManagedOrganization;members:{user_id:string;login:string;role:string|null}[];events:{id:string;action:string;actor:string|null;subject:string|null;created_at:string}[]};
export function OrganizationAccess({organization,onChanged}:{organization:ManagedOrganization;onChanged:()=>void}){
  const [open,setOpen]=useState(false);
  return <details className="workspace-organisation" onToggle={event=>setOpen(event.currentTarget.open)}><summary>{organization.name} · organisation administration<span>{organization.role} · {organization.workspace_limit} workspace allowance</span></summary>{open?<AccessEditor organization={organization} onChanged={onChanged}/>:null}</details>;
}
function AccessEditor({organization,onChanged}:{organization:ManagedOrganization;onChanged:()=>void}){
  const id=organization.id;
  const [data,setData]=useState<Access|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();void fetch(`/api/organizations/${id}/access`,{signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error??'Could not load organisation access.');if(!controller.signal.aborted)setData(body);}).catch(err=>{if(!controller.signal.aborted){setData(null);setError(err.message);}});return()=>controller.abort();},[id,revision]);
  async function save(userId:string,role:string|null){
    if(busy)return;setBusy(true);setError('');try{const response=await fetch(`/api/organizations/${id}/access/${encodeURIComponent(userId)}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({role})});const body=await response.json();if(!response.ok)throw new Error(body.error??'Could not save organisation access.');setRevision(v=>v+1);onChanged();window.dispatchEvent(new Event('nospoilers:workspaces-changed'));}catch(err){setError(err instanceof Error?err.message:'Could not save organisation access.');}finally{setBusy(false);}
  }
  const access=<section className="workspace-organisation-section"><div className="workspace-section-heading"><div><h3>Organisation access</h3><p>Owners manage administrators. Workspace membership is managed separately.</p></div></div><p className="workspace-form-note">Administrators can create workspaces within the shared allowance. These permissions do not grant access to every workspace or connect anyone’s GitHub account.</p>{!data&&!error?<WatchSkeleton variant="list" className="mt-4" />:null}{data?<><p className="workspace-form-note">Active workspace allowance: {data.organization.workspace_limit}. This is not a per-workspace scan allowance.</p><div className="workspace-member-list">{data.members.map(member=><OrganizationMember key={`${member.user_id}:${member.role}`} member={member} editable={data.organization.role==='owner'} busy={busy} save={role=>save(member.user_id,role)}/>)}</div></>:null}</section>;
  const activity=<section className="workspace-organisation-section"><div className="workspace-section-heading"><div><h3>Administration activity</h3><p>Recorded changes to organisation access.</p></div></div>{!data&&!error?<WatchSkeleton variant="list" className="mt-4" />:data?.events.length?<ol className="workspace-administration-events">{data.events.map(event=><li key={event.id}><div><strong>{event.action.replaceAll('_',' ')}</strong><p>{event.actor??'Former user'} → {event.subject??'Former user'}</p></div><time dateTime={event.created_at}>{new Date(event.created_at).toLocaleString()}</time></li>)}</ol>:<p className="workspace-form-note">No administration changes recorded.</p>}</section>;
  return <div className="workspace-organisation-content">{error?<div role="alert">{error}<Button variant="outline" onClick={()=>{setError('');setRevision(v=>v+1);}}>Retry organisation access</Button></div>:null}<SettingsTabs label={`${organization.name} administration`} defaultValue="access" tabs={[{id:'access',label:'Access',content:access},{id:'activity',label:'Activity',content:activity},...(organization.billing_available?[{id:'billing',label:'Billing',content:<OrganizationBilling key={organization.id} id={organization.id}/>}]:[]),...(organization.role==='owner'?[{id:'deletion',label:'Deletion review',content:<WorkspaceDeletionRequest organizationId={organization.id}/>}]:[])]}/></div>;
}
function OrganizationMember({member,editable,busy,save}:{member:Access['members'][number];editable:boolean;busy:boolean;save:(role:string|null)=>Promise<void>}){
  const [role,setRole]=useState(member.role??'');
  return <div className="workspace-member-row"><div><strong>{member.login}</strong><p>{member.role??'Workspace access only'}</p></div>{editable?<form onSubmit={event=>{event.preventDefault();void save(role||null);}}><label>Organisation role for {member.login}<Select value={role||'__no_admin__'} onValueChange={value=>setRole(value==='__no_admin__'?'':value)}><SelectTrigger aria-label={`Organisation role for ${member.login}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__no_admin__">No organisation administration</SelectItem><SelectItem value="admin">Administrator</SelectItem><SelectItem value="owner">Owner</SelectItem></SelectContent></Select></label><Button type="submit" disabled={busy||role===(member.role??'')}>Save organisation role for {member.login}</Button></form>:null}</div>;
}
