import {WatchPageHeader} from "./WatchPageHeader";
import { WatchSkeleton } from "@/components/WatchDataState";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/motion/select';
import {navigate} from '@/nav';
import {workspaceInstallationIds,type ProductWorkspace} from '@/watch/workspace-types';
import {WorkspaceInvitationInbox} from './WorkspaceTeam';
import {OrganizationAccess,type ManagedOrganization} from './OrganizationAccess';
import {WorkspaceConnectionPlacement} from './WorkspaceConnectionPlacement';
import {WorkspaceDeletionRequest} from './WorkspaceDeletionRequest';
import {SettingsTabs} from './design/SettingsTabs';
import './workspace-settings.css';

type WorkspaceListRow = ProductWorkspace & {avatar_url?: string | null};
function WorkspaceAvatar({name,url}:{name:string;url?:string|null}){
  const [failed,setFailed]=useState(false);
  const initials=name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(part=>Array.from(part)[0]).join('').toUpperCase()||'W';
  return <span aria-hidden="true" className="flex size-8 shrink-0 items-center justify-center overflow-hidden rounded-md border border-white/10 bg-white/5 text-xs font-medium text-snow">
    {url&&!failed?<img src={url} alt="" className="size-full object-cover" onError={()=>setFailed(true)}/>:initials}
  </span>;
}

export function WorkspaceManagement(){
  const readTab=()=>new URLSearchParams(window.location.search).get('workspaceTab')??'workspaces';
  const [tab,setTab]=useState(readTab);
  const [rows,setRows]=useState<WorkspaceListRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
  const [revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[name,setName]=useState(''),[organization,setOrganization]=useState('');
  const [renameId,setRenameId]=useState<string|null>(null),[rename,setRename]=useState('');
  const [notice,setNotice]=useState('');
  const [managedId,setManagedId]=useState<string|null>(null);
  const [reviewHistory,setReviewHistory]=useState(false);
  const [listFailed,setListFailed]=useState(false);
  const [organizations,setOrganizations]=useState<ManagedOrganization[]>([]);
  const selectedOrganization=organization?organizations.find(row=>row.id===organization):organizations[0];
  useEffect(()=>{const sync=()=>setTab(readTab());window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
  useEffect(()=>{const controller=new AbortController();void fetch('/api/workspaces',{signal:controller.signal}).then(async response=>{
    if(!response.ok)throw new Error('Could not load workspaces.');const body=await response.json() as {workspaces:WorkspaceListRow[];organizations?:ManagedOrganization[]};if(!Array.isArray(body.workspaces)||(body.organizations!==undefined&&!Array.isArray(body.organizations)))throw new Error('Could not load workspaces.');if(!controller.signal.aborted){setRows(body.workspaces);setOrganizations(body.organizations??[]);setListFailed(false);setLoading(false);}
  }).catch(err=>{if(!controller.signal.aborted){setRows([]);setOrganizations([]);setListFailed(true);setError(err instanceof Error?err.message:'Could not load workspaces.');setLoading(false);}});return()=>controller.abort();},[revision]);
  async function mutate(path:string,method:string,body:unknown,reset?:{creation?:boolean;renameId?:string}){
    if(busy||loading)return;setBusy(true);setError(null);setNotice('');
    try{const response=await fetch(path,{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??'Could not save workspace.');setNotice('Workspace saved. Existing evidence and subscription allowances are unchanged.');if(reset?.creation)setName('');if(reset?.renameId)setRenameId(current=>current===reset.renameId?null:current);setLoading(true);setRevision(value=>value+1);window.dispatchEvent(new Event('nospoilers:workspaces-changed'));}
    catch(err){setError(err instanceof Error?err.message:'Could not save workspace.');}finally{setBusy(false);}
  }
  const managed=rows.find(row=>row.id===managedId);
  const workspaceList=<>
    <WorkspaceInvitationInbox/>
    {loading?<WatchSkeleton variant="list" className="mt-4" />:listFailed?null:rows.length?<div className="workspace-journey-table-wrap"><table className="workspace-journey-table"><thead><tr><th scope="col">Workspace</th><th scope="col">Your role</th><th scope="col">Connections</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(workspace=><tr key={workspace.id}><td><div className="workspace-row-main"><WorkspaceAvatar key={`${workspace.id}:${workspace.avatar_url??''}`} name={workspace.name} url={workspace.avatar_url}/><div className="workspace-row-identity"><h3>{workspace.name}</h3><p>{workspace.archived_at?'Archived · evidence retained':'Active workspace'}</p></div></div></td><td><span className="capitalize">{workspace.role}</span></td><td>{workspaceInstallationIds(workspace).length?`${workspaceInstallationIds(workspace).length} GitHub`:'No GitHub connection'}</td><td><div className="workspace-row-actions"><Button variant="ghost" onClick={()=>{const p=new URLSearchParams({workspace:workspace.id});if(workspace.installation_id)p.set('install',String(workspace.installation_id));navigate(`/watch?${p}`);}}>Open workspace</Button><Button variant="ghost" aria-label={`Manage ${workspace.name}`} aria-expanded={managedId===workspace.id} aria-controls="workspace-management-panel" onClick={()=>{setManagedId(managedId===workspace.id?null:workspace.id);setRenameId(null);setReviewHistory(false);}}>Manage</Button></div></td></tr>)}</tbody></table></div>:<div className="workspace-settings-empty"><h3>No workspaces yet</h3><p>Accepted invitations and workspaces you create appear here.</p></div>}
    {!loading&&!listFailed&&managed?<section id="workspace-management-panel" aria-label={`Manage ${managed.name}`} className="workspace-manage-panel"><div className="workspace-section-heading"><div><h2>{managed.name}</h2><p>Workspace access and administration.</p></div><Button variant="ghost" onClick={()=>{setManagedId(null);setRenameId(null);setReviewHistory(false);}}>Close</Button></div><div className="workspace-management-option"><div><h3>Team & access</h3><p>Manage named invitations and workspace roles.</p></div><Button variant="outline" onClick={()=>navigate(`/watch/team?workspace=${managed.id}`)}>Team & access</Button></div>
    {['owner','admin'].includes(managed.role)?<><div className="workspace-management-option"><div><h3>Workspace name</h3><p>Change the name shown to your team.</p></div><Button variant="outline" disabled={busy} onClick={()=>{setRenameId(managed.id);setRename(managed.name);}}>Rename</Button></div>{renameId===managed.id?<form className="workspace-rename-form" onSubmit={event=>{event.preventDefault();void mutate(`/api/workspaces/${managed.id}`,'PATCH',{name:rename},{renameId:managed.id});}}><input aria-label="Workspace name" maxLength={100} value={rename} disabled={busy} onChange={event=>setRename(event.target.value)}/><Button type="submit" disabled={busy||!rename.trim()}>Save name</Button><Button type="button" variant="ghost" onClick={()=>setRenameId(null)}>Cancel</Button></form>:null}<div className="workspace-management-option"><div><h3>{managed.archived_at?'Restore workspace':'Archive workspace'}</h3><p>Existing evidence is retained. Connected and migrated default workspaces cannot yet be archived.</p></div><Button variant="outline" disabled={busy} onClick={()=>void mutate(`/api/workspaces/${managed.id}`,'PATCH',{archived:!managed.archived_at})}>{managed.archived_at?'Restore':'Archive'}</Button></div></>:null}
    {organizations.some(o=>o.id===managed.organization_id&&o.role==='owner')?<div className="workspace-history-review"><div className="workspace-management-option"><div><h3>History deletion review</h3><p>Review impact and eligibility before requesting deletion.</p></div><Button variant="outline" onClick={()=>setReviewHistory(current=>!current)} aria-expanded={reviewHistory}>{reviewHistory?'Close review':'Review deletion'}</Button></div>{reviewHistory?<WorkspaceDeletionRequest organizationId={managed.organization_id} workspaceId={managed.id} workspaceName={managed.name}/>:null}</div>:null}
    </section>:null}
    <p className="workspace-journey-note">Create another workspace from the workspace switcher in the sidebar.</p>
  </>;
  const creation=loading?<WatchSkeleton variant="list" className="mt-4"/>:listFailed?null:organizations.length?<form className="workspace-create workspace-settings-form" onSubmit={event=>{event.preventDefault();if(selectedOrganization)void mutate('/api/workspaces','POST',{organizationId:selectedOrganization.id,name},{creation:true});}}><div className="workspace-section-heading"><div><h2>Create a workspace</h2><p>A separate home for a project’s evidence and team.</p></div></div><label>Organisation<Select value={selectedOrganization?.id??''} onValueChange={setOrganization} disabled={busy}><SelectTrigger aria-label="Organisation"><SelectValue placeholder="Choose an organisation"/></SelectTrigger><SelectContent>{organizations.map(row=><SelectItem key={row.id} value={row.id}>{row.name} · existing subscription</SelectItem>)}</SelectContent></Select></label><label>Workspace name<input required maxLength={100} value={name} disabled={busy} onChange={event=>setName(event.target.value)} placeholder="For example, Production"/></label><p className="workspace-form-note">Uses the organisation’s existing subscription and scan allowance. Creating a workspace does not restart the trial. Migrated default and connected workspaces cannot yet be archived.</p><Button type="submit" disabled={busy||!selectedOrganization||!name.trim()}>{busy?'Saving…':'Create workspace'}</Button></form>:<div className="workspace-settings-empty"><h2>Create a workspace</h2><p>An organisation owner or administrator can create workspaces within the shared allowance.</p></div>;
  const connections=listFailed?null:<><div className="workspace-section-heading"><div><h2>Connection placement</h2><p>Move an unused GitHub connection between workspaces in the same organisation.</p></div></div><WorkspaceConnectionPlacement workspaces={rows} organizationIds={organizations.map(o=>o.id)} onChanged={()=>setRevision(v=>v+1)}/>{!loading&&!rows.some(w=>!w.archived_at&&['owner','admin'].includes(w.role)&&organizations.some(o=>o.id===w.organization_id)&&workspaceInstallationIds(w).length)?<div className="workspace-settings-empty"><h3>No connections available to place</h3><p>Connect GitHub in a workspace you administer. Only connections without repositories, scans or history can move.</p></div>:null}</>;
  const administration=listFailed?null:<><div className="workspace-section-heading"><div><h2>Organisation settings</h2><p>Shared administration, subscription and history controls.</p></div></div>{organizations.length?<div className="workspace-organisation-list">{organizations.map(organization=><OrganizationAccess key={organization.id} organization={organization} onChanged={()=>setRevision(v=>v+1)}/>)}</div>:loading?null:<div className="workspace-settings-empty"><h3>No organisation administration access</h3><p>Your workspace role still controls the evidence and tools you can use.</p></div>}</>;
  return <section className="workspace-management workspace-settings"><WatchPageHeader title="A home for every release." lede="Keep sources, people and evidence in the right workspace."/>
    {error?<div role="alert" className="watch-empty"><p>{error}</p><Button variant="outline" onClick={()=>{setError(null);setLoading(true);setRevision(value=>value+1);}}>Retry</Button></div>:null}
    {notice?<p role="status" className="mt-4 text-sm text-mute">{notice}</p>:null}
    <SettingsTabs label="Workspace settings" value={['workspaces','create','connections','organisation'].includes(tab)?tab:'workspaces'} onValueChange={value=>{setTab(value);const query=new URLSearchParams(window.location.search);if(value==='workspaces')query.delete('workspaceTab');else query.set('workspaceTab',value);navigate(`/watch/workspaces${query.size?`?${query}`:''}`);}} tabs={[{id:'workspaces',label:'Workspaces',content:workspaceList},...(tab==='create'||name?[{id:'create',label:'Create workspace',content:creation}]:[]),{id:'connections',label:'Connections',content:connections},{id:'organisation',label:'Organisation',content:administration}]}/>
  </section>;
}
